(function(){
'use strict';
const $=id=>document.getElementById(id);
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
let state={items:[],phase:null,index:0,step:null,afterIndex:0,afterStep:null};
let bypassTreatment=false,bypassReport=false;
function ensureView(){if($('causalView'))return;const s=document.createElement('section');s.id='causalView';s.className='card hidden';s.innerHTML='<div class="questionTop"><span class="pill">Validação causal</span><span id="causalCounter" class="muted"></span></div><div class="progress"><span id="causalProgress"></span></div><p id="causalMicro" class="microInstruction">Consulte o pêndulo</p><h2 id="causalTitle"></h2><p id="causalContext" class="causalContext muted"></p><div id="causalAnswers" class="answerGrid"><button class="answer yes" data-causal-answer="yes">Sim</button><button class="answer no" data-causal-answer="no">Não</button></div><div id="causalSummary" class="hidden"></div>';document.querySelector('main')?.appendChild(s);s.querySelectorAll('[data-causal-answer]').forEach(b=>b.addEventListener('click',()=>answer(b.dataset.causalAnswer==='yes')))}
function hideMain(){['homeView','startView','questionView','priorityView','treatmentView','reportView','historyView'].forEach(id=>$(id)?.classList.add('hidden'));$('causalView')?.classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}
function findings(){return Array.from(document.querySelectorAll('#priorityList .check')).map((el,i)=>({id:'finding_'+i,label:el.querySelector('b')?.textContent.trim()||('Item '+(i+1)),command:(el.querySelector('small')?.textContent||'').replace(/^Comando sugerido:\s*/i,'').trim(),root:null,priorCause:null,priorIdentified:null,priorOrigins:{internal:false,external:false,ancestral:false,spiritual:false},needsDeeper:null,treat:null,priority:null,neutralized:null,followup:null,element:el}))}
function setQuestion(title,context,counter,pct){$('causalTitle').textContent=title;$('causalContext').textContent=context||'';$('causalCounter').textContent=counter;$('causalProgress').style.width=pct+'%';$('causalAnswers').classList.remove('hidden');$('causalSummary').classList.add('hidden')}
function startPre(){state={items:findings(),phase:'pre',index:0,step:'root',afterIndex:0,afterStep:null};window.__causalReview={export:exportState};if(!state.items.length){continueTreatment();return}hideMain();renderPre()}
function progress(){const n=Math.max(state.items.length,1);const offsets={root:0,prior:.12,identified:.24,originInternal:.36,originExternal:.46,originAncestral:.56,originSpiritual:.66,deeper:.76,treat:.86,priority:.94};return Math.min(99,Math.round((state.index+(offsets[state.step]||0))/n*100))}
function renderPre(){const it=state.items[state.index],n=state.items.length;if(!it){showPlan();return}const ctx='Achado: '+it.label,ct=(state.index+1)+' de '+n,p=progress();
 if(state.step==='root')setQuestion('Este achado é uma causa raiz ativa, e não apenas uma consequência?',ctx,ct,p);
 else if(state.step==='prior')setQuestion('Há uma causa anterior a este achado que precisa ser considerada?',ctx,ct,p);
 else if(state.step==='identified')setQuestion('Essa causa anterior já foi identificada em outro ramo desta investigação?',ctx,ct,p);
 else if(state.step==='originInternal')setQuestion('A causa anterior ainda não delimitada tem origem interna — como crença, emoção, identidade, comportamento ou experiência?',ctx,ct,p);
 else if(state.step==='originExternal')setQuestion('Essa causa anterior tem origem externa — como ambiente, contexto, relacionamento ou fator objetivo?',ctx,ct,p);
 else if(state.step==='originAncestral')setQuestion('Essa causa anterior está relacionada a padrão familiar, ancestral ou transgeracional?',ctx,ct,p);
 else if(state.step==='originSpiritual')setQuestion('Dentro da sua prática, essa causa anterior é espiritual, simbólica ou energética?',ctx,ct,p);
 else if(state.step==='deeper')setQuestion('Essa causa anterior precisa ser identificada com mais detalhe antes de tratar este achado?',ctx,ct,p);
 else if(state.step==='treat')setQuestion('Este achado deve ser tratado nesta sessão?',ctx,ct,p);
 else if(state.step==='priority')setQuestion('Este achado precisa ser tratado antes dos demais itens identificados?',ctx,ct,p)}
function answerPre(yes){const it=state.items[state.index];
 if(state.step==='root'){it.root=yes;state.step=yes?'treat':'prior'}
 else if(state.step==='prior'){it.priorCause=yes;state.step=yes?'identified':'treat'}
 else if(state.step==='identified'){it.priorIdentified=yes;state.step=yes?'treat':'originInternal'}
 else if(state.step==='originInternal'){it.priorOrigins.internal=yes;state.step='originExternal'}
 else if(state.step==='originExternal'){it.priorOrigins.external=yes;state.step='originAncestral'}
 else if(state.step==='originAncestral'){it.priorOrigins.ancestral=yes;state.step='originSpiritual'}
 else if(state.step==='originSpiritual'){it.priorOrigins.spiritual=yes;state.step='deeper'}
 else if(state.step==='deeper'){it.needsDeeper=yes;state.step='treat'}
 else if(state.step==='treat'){it.treat=yes;if(yes)state.step='priority';else nextPre()}
 else if(state.step==='priority'){it.priority=yes;nextPre()}
 renderPre()}
function nextPre(){state.index++;state.step='root'}
function originText(it){const labels=[];if(it.priorOrigins?.internal)labels.push('interna');if(it.priorOrigins?.external)labels.push('externa');if(it.priorOrigins?.ancestral)labels.push('familiar/ancestral');if(it.priorOrigins?.spiritual)labels.push('espiritual/simbólica');return labels.join(', ')}
function classification(it){let a=it.root===true?'Causa raiz':it.priorCause===true?(it.priorIdentified===false?'Consequência • causa anterior ainda não delimitada':'Consequência de causa anterior'):'Fator intermediário / associado';if(it.priorIdentified===false&&originText(it))a+=' • origem possível: '+originText(it);if(it.needsDeeper===true)a+=' • aprofundar antes';if(it.treat===false)a+=' • não tratar nesta sessão';else if(it.priority===true)a+=' • prioridade';return a}
function orderedItems(){return state.items.slice().sort((a,b)=>Number(b.treat===true)-Number(a.treat===true)||Number(b.priority===true)-Number(a.priority===true)||Number(b.root===true)-Number(a.root===true)||Number(a.needsDeeper===true)-Number(b.needsDeeper===true))}
function showPlan(){state.phase='plan';$('causalProgress').style.width='100%';$('causalCounter').textContent='Plano';$('causalMicro').textContent='Resultado da validação';$('causalTitle').textContent='Ordem de tratamento desta sessão';$('causalContext').textContent='A ordem abaixo foi organizada a partir das respostas registradas. Itens marcados para aprofundamento aparecem sinalizados.';$('causalAnswers').classList.add('hidden');const host=$('causalSummary');host.classList.remove('hidden');const ordered=orderedItems();host.innerHTML='<div class="causalPlan">'+ordered.map((it,i)=>`<div class="causalPlanItem ${it.treat===false?'causalDeferred':''}"><span class="pill">${i+1}</span><div><b>${esc(it.label)}</b><small>${esc(classification(it))}</small>${it.needsDeeper===true?'<small class="causalWarn">Identifique melhor a causa anterior antes de considerar este item resolvido.</small>':''}</div></div>`).join('')+'</div><button id="causalContinue" class="primary wide">Continuar para tratamento</button>';$('#causalContinue').onclick=continueTreatment}
function continueTreatment(){const list=$('priorityList');if(list&&state.items.length)orderedItems().forEach(it=>{it.element.dataset.causal=classification(it);list.appendChild(it.element)});$('causalView')?.classList.add('hidden');$('priorityView')?.classList.remove('hidden');bypassTreatment=true;$('toTreatmentBtn')?.click();setTimeout(annotateTreatment,40)}
function annotateTreatment(){const cards=Array.from(document.querySelectorAll('#treatmentItems .treatmentCard')),ordered=orderedItems();cards.forEach((card,i)=>{const it=ordered[i];if(!it)return;card.querySelector('.causalBadge')?.remove();const p=document.createElement('p');p.className='causalBadge';p.textContent=classification(it);card.insertBefore(p,card.querySelector('.fieldTitle'));if(it.treat===false)card.classList.add('causalDeferred');if(it.needsDeeper===true){const note=document.createElement('div');note.className='causalNotice';note.textContent='A investigação indicou uma causa anterior ainda não totalmente delimitada. Registre o tratamento deste item apenas se isso também foi indicado.';card.insertBefore(note,card.querySelector('.fieldTitle'))}})}
function startPost(){const todo=orderedItems().filter(x=>x.treat===true);if(!todo.length){continueReport();return}state.phase='post';state.afterItems=todo;state.afterIndex=0;state.afterStep='neutralized';hideMain();renderPost()}
function renderPost(){const arr=state.afterItems,it=arr[state.afterIndex],n=arr.length;if(!it){continueReport();return}const pct=Math.round((state.afterIndex+(state.afterStep==='neutralized'?0:.5))/n*100),ctx='Achado tratado: '+it.label;if(state.afterStep==='neutralized')setQuestion('Após o tratamento, este fator foi neutralizado suficientemente nesta sessão?',ctx,(state.afterIndex+1)+' de '+n,pct);else setQuestion('Este fator precisa de uma nova sessão específica de acompanhamento?',ctx,(state.afterIndex+1)+' de '+n,pct)}
function answerPost(yes){const it=state.afterItems[state.afterIndex];if(state.afterStep==='neutralized'){it.neutralized=yes;if(yes){it.followup=false;state.afterIndex++;state.afterStep='neutralized'}else state.afterStep='followup'}else{it.followup=yes;state.afterIndex++;state.afterStep='neutralized'}renderPost()}
function answer(yes){if(state.phase==='pre')answerPre(yes);else if(state.phase==='post')answerPost(yes)}
function exportState(){return {items:state.items.map(({element,...x})=>x),ordered:orderedItems().map(x=>x.id)}}
function persistCausal(){try{const h=JSON.parse(localStorage.getItem('rt_rich_sessions')||'[]');if(h.length){h[0].causal=exportState();localStorage.setItem('rt_rich_sessions',JSON.stringify(h))}}catch(e){}}
function continueReport(){$('causalView')?.classList.add('hidden');$('treatmentView')?.classList.remove('hidden');bypassReport=true;$('makeReportBtn')?.click();setTimeout(()=>{persistCausal();appendCausalReport()},100)}
function postText(it){return it.neutralized===true?'Neutralizado suficientemente nesta sessão':it.neutralized===false?(it.followup===true?'Não neutralizado • nova sessão indicada':'Não neutralizado • sem nova sessão indicada'):'Não registrada'}
function appendCausalReport(){const body=$('reportBody');if(!body||!state.items.length)return;body.querySelector('.causalReport')?.remove();const sec=document.createElement('section');sec.className='card reportSection causalReport';sec.innerHTML='<h3>Validação causal e ordem de tratamento</h3>'+orderedItems().map((it,i)=>`<div class="reportTreatment"><h4>${i+1}. ${esc(it.label)}</h4><p><b>Classificação:</b> ${esc(classification(it))}</p>${it.priorIdentified===false&&originText(it)?`<p><b>Origem indicada para aprofundamento:</b> ${esc(originText(it))}</p>`:''}${it.treat===true?`<p><b>Validação após tratamento:</b> ${esc(postText(it))}</p>`:''}</div>`).join('');body.appendChild(sec)}
function decorateHistory(){setTimeout(()=>{let h=[];try{h=JSON.parse(localStorage.getItem('rt_rich_sessions')||'[]')}catch(e){}const cards=Array.from(document.querySelectorAll('#historyList .historyCard:not(.legacy)'));cards.forEach((card,i)=>{const c=h[i]?.causal;if(!c?.items?.length||card.querySelector('.historyCausal'))return;const box=card.querySelector('.historyDetails');if(!box)return;const order=c.ordered||[];const d=document.createElement('div');d.className='historyFinding historyCausal';d.innerHTML='<b>Validação causal e ordem</b><ol>'+c.items.slice().sort((a,b)=>order.indexOf(a.id)-order.indexOf(b.id)).map(it=>`<li><b>${esc(it.label)}</b><br><span>${esc(classification(it))}</span>${it.priorIdentified===false&&originText(it)?`<br><span>Origem para aprofundamento: ${esc(originText(it))}</span>`:''}${it.treat===true?`<br><span>${esc(postText(it))}</span>`:''}</li>`).join('')+'</ol>';box.appendChild(d)})},60)}
function install(){ensureView();$('toTreatmentBtn')?.addEventListener('click',e=>{if(bypassTreatment){bypassTreatment=false;return}e.preventDefault();e.stopImmediatePropagation();startPre()},true);$('makeReportBtn')?.addEventListener('click',e=>{if(bypassReport){bypassReport=false;return}e.preventDefault();e.stopImmediatePropagation();startPost()},true);$('historyBtn')?.addEventListener('click',decorateHistory)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();