(function(){
'use strict';

const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const unitLabel=(n,u)=>{const q=Number(n);if(!q)return '';const singular={minutos:'minuto',horas:'hora',dias:'dia',semanas:'semana',meses:'mês'};return `${q} ${q===1?(singular[u]||u):u}`};

let session=null;
let currentQuestionId=null;
let answeredOrder=[];
let maxProgress=0;
let causal={items:[],index:0,step:'root',phase:'pre'};
let treatmentRecords=[];

function allViews(){return ['homeView','startView','questionView','priorityView','treatmentView','reportView','historyView','causalView']}
function show(id){allViews().forEach(v=>$(v)?.classList.add('hidden'));$(id)?.classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}
function activeMode(){return session?.mode||document.querySelector('.tab.active')?.dataset.mode||'finance'}
function protocol(mode){return DATA[mode]}
function plan(tag){return PLANS[tag]||{label:tag,command:'Investigar e formular um comando específico para este achado.'}}
function sanitizeQuestions(mode){const src=protocol(mode)?.questions||[],seen=new Set();return src.filter(q=>q&&q.id&&!seen.has(q.id)&&(seen.add(q.id),true))}
function questionMap(){return new Map(session.questions.map(q=>[q.id,q]))}
function isEligible(q){return !q.parent||session.answers[q.parent]==='yes'}
function descendantsOf(id){const out=new Set(),qs=session.questions;let changed=true;while(changed){changed=false;qs.forEach(q=>{if(q.parent&&(q.parent===id||out.has(q.parent))&&!out.has(q.id)){out.add(q.id);changed=true}})}return out}
function cleanupIneligible(){const map=questionMap();Object.keys(session.answers).forEach(id=>{const q=map.get(id);if(!q||!isEligible(q)){delete session.answers[id];answeredOrder=answeredOrder.filter(x=>x!==id)}})}
function recomputeFindings(){const seen=new Set();session.findings=[];session.questions.forEach(q=>{if(q.tag&&session.answers[q.id]==='yes'&&!seen.has(q.tag)){seen.add(q.tag);session.findings.push(q.tag)}})}
function nextUnanswered(){cleanupIneligible();return session.questions.find(q=>isEligible(q)&&session.answers[q.id]===undefined)||null}
function progressPercent(){const eligible=session.questions.filter(isEligible),answered=eligible.filter(q=>session.answers[q.id]!==undefined).length;let p=eligible.length?Math.round(answered/eligible.length*100):0;if(p<100)p=Math.min(96,p);maxProgress=Math.max(maxProgress,p);return maxProgress}
function setProgress(p){$('counter').textContent=`${p}%`;$('progressBar').style.width=`${p}%`}

function goHome(){session=null;currentQuestionId=null;answeredOrder=[];maxProgress=0;treatmentRecords=[];show('homeView')}
function openProtocol(mode){document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.mode===mode));const data=protocol(mode);$('startTitle').textContent=data?.title||mode;$('initialIntensity').value=50;$('initialOut').textContent='50%';show('startView')}
function startInvestigation(){const mode=document.querySelector('.tab.active')?.dataset.mode||'finance';session={id:Date.now(),date:new Date().toISOString(),mode,title:protocol(mode).title,questions:sanitizeQuestions(mode),answers:{},findings:[],initial:Number($('initialIntensity').value||0),final:null,generalNotes:'',causal:null,treatment:[]};answeredOrder=[];maxProgress=0;currentQuestionId=nextUnanswered()?.id||null;if(!currentQuestionId)return finishInvestigation();show('questionView');renderQuestion()}
function renderQuestion(){const q=questionMap().get(currentQuestionId);if(!q)return finishInvestigation();$('sectionPill').textContent=q.section||'Investigação';$('question').textContent=q.q;setProgress(progressPercent())}
function answerInvestigation(value){const q=questionMap().get(currentQuestionId);if(!q)return;session.answers[q.id]=value;if(!answeredOrder.includes(q.id))answeredOrder.push(q.id);if(value==='no'){const desc=descendantsOf(q.id);desc.forEach(id=>delete session.answers[id]);answeredOrder=answeredOrder.filter(id=>!desc.has(id))}recomputeFindings();const next=nextUnanswered();if(next){currentQuestionId=next.id;renderQuestion()}else finishInvestigation()}
function backQuestion(){if(!answeredOrder.length)return;const id=answeredOrder.pop();delete session.answers[id];const desc=descendantsOf(id);desc.forEach(x=>delete session.answers[x]);answeredOrder=answeredOrder.filter(x=>!desc.has(x));recomputeFindings();currentQuestionId=id;maxProgress=Math.max(0,maxProgress-2);renderQuestion()}
function finishInvestigation(){recomputeFindings();renderFindings();show('priorityView')}
function renderFindings(){const host=$('priorityList');host.innerHTML='';if(!session.findings.length){host.innerHTML='<p class="muted">Nenhum item específico foi identificado nos ramos respondidos.</p>';return}session.findings.forEach(tag=>{const p=plan(tag),d=document.createElement('div');d.className='check';d.dataset.tag=tag;d.innerHTML=`<b>${esc(p.label)}</b><small><strong>Comando sugerido:</strong> ${esc(p.command)}</small>`;host.appendChild(d)})}

function ensureCausalView(){if($('causalView'))return;const s=document.createElement('section');s.id='causalView';s.className='card hidden';s.innerHTML='<div class="questionTop"><span class="pill">Validação causal</span><span id="causalPercent" class="muted"></span></div><div class="progress"><span id="causalProgress"></span></div><p class="microInstruction">Consulte o pêndulo</p><h2 id="causalTitle"></h2><p id="causalContext" class="muted"></p><div id="causalAnswers" class="answerGrid"><button class="answer yes" data-causal="yes">Sim</button><button class="answer no" data-causal="no">Não</button></div><div id="causalPlan" class="hidden"></div>';document.querySelector('main')?.appendChild(s);s.querySelectorAll('[data-causal]').forEach(b=>b.addEventListener('click',()=>answerCausal(b.dataset.causal==='yes')))}
function startCausal(){ensureCausalView();causal={phase:'pre',index:0,step:'root',items:session.findings.map((tag,i)=>({id:`f_${i}`,tag,label:plan(tag).label,command:plan(tag).command,root:null,priorCause:null,priorIdentified:null,origin:null,deepenPrior:null,treat:null,priority:null,neutralized:null,followup:null}))};if(!causal.items.length)return startTreatment();show('causalView');renderCausal()}
function causalStepsDone(){let n=0;causal.items.forEach(it=>{['root','priorCause','priorIdentified','origin','deepenPrior','treat','priority','neutralized','followup'].forEach(k=>{if(it[k]!==null)n++})});return n}
function causalPct(){const approxTotal=Math.max(1,causal.items.length*5);return Math.min(96,Math.round(causalStepsDone()/approxTotal*100))}
function setCausalQuestion(title,ctx){$('causalTitle').textContent=title;$('causalContext').textContent=ctx;$('causalPercent').textContent=`${causalPct()}%`;$('causalProgress').style.width=`${causalPct()}%`;$('causalAnswers').classList.remove('hidden');$('causalPlan').classList.add('hidden')}
function renderCausal(){const it=causal.items[causal.index];if(!it)return showCausalPlan();const ctx=`Achado: ${it.label}`;switch(causal.step){case'root':setCausalQuestion('Este achado é uma causa raiz ativa, e não apenas uma consequência?',ctx);break;case'prior':setCausalQuestion('Há uma causa anterior a este achado que precisa ser considerada?',ctx);break;case'identified':setCausalQuestion('Essa causa anterior já foi identificada em outro ramo desta investigação?',ctx);break;case'originInternal':setCausalQuestion('A causa anterior parece ser predominantemente interna?',ctx);break;case'originExternal':setCausalQuestion('A causa anterior parece ser predominantemente externa?',ctx);break;case'originFamily':setCausalQuestion('A causa anterior parece ser familiar, ancestral ou transgeracional?',ctx);break;case'originSpiritual':setCausalQuestion('Dentro da sua prática, a causa anterior parece ser espiritual, simbólica ou energética?',ctx);break;case'deepen':setCausalQuestion('Essa causa anterior precisa ser aprofundada antes de tratar este achado?',ctx);break;case'treat':setCausalQuestion('Este achado deve ser tratado nesta sessão?',ctx);break;case'priority':setCausalQuestion('Este achado precisa ser tratado antes dos demais itens identificados?',ctx);break}}
function nextCausalItem(){causal.index++;causal.step='root';renderCausal()}
function answerCausal(yes){const it=causal.items[causal.index];if(!it)return;switch(causal.step){case'root':it.root=yes;causal.step=yes?'treat':'prior';break;case'prior':it.priorCause=yes;causal.step=yes?'identified':'treat';break;case'identified':it.priorIdentified=yes;causal.step=yes?'treat':'originInternal';break;case'originInternal':if(yes){it.origin='Interna';causal.step='deepen'}else causal.step='originExternal';break;case'originExternal':if(yes){it.origin='Externa';causal.step='deepen'}else causal.step='originFamily';break;case'originFamily':if(yes){it.origin='Familiar / ancestral';causal.step='deepen'}else causal.step='originSpiritual';break;case'originSpiritual':it.origin=yes?'Espiritual / simbólica':'Não delimitada';causal.step='deepen';break;case'deepen':it.deepenPrior=yes;causal.step='treat';break;case'treat':it.treat=yes;if(yes)causal.step='priority';else nextCausalItem();break;case'priority':it.priority=yes;nextCausalItem();break}if(causal.index<causal.items.length)renderCausal()}
function classification(it){if(it.root===true)return it.priority?'Causa raiz • prioridade':'Causa raiz';if(it.priorCause===true){let s=it.priorIdentified?'Consequência de causa anterior identificada':'Consequência de causa anterior';if(it.origin)s+=` • origem ${it.origin.toLowerCase()}`;if(it.deepenPrior)s+=' • aprofundar antes';return s}return 'Fator associado / intermediário'}
function orderedCausal(){return causal.items.slice().sort((a,b)=>Number(b.treat===true)-Number(a.treat===true)||Number(b.priority===true)-Number(a.priority===true)||Number(b.root===true)-Number(a.root===true))}
function showCausalPlan(){session.causal={items:causal.items,ordered:orderedCausal().map(x=>x.id)};$('causalPercent').textContent='100%';$('causalProgress').style.width='100%';$('causalTitle').textContent='Ordem de tratamento';$('causalContext').textContent='Revise a classificação antes de continuar.';$('causalAnswers').classList.add('hidden');const host=$('causalPlan');host.classList.remove('hidden');host.innerHTML='<div class="causalPlanList">'+orderedCausal().map((it,i)=>`<div class="causalPlanItem"><span class="pill">${i+1}</span><div><b>${esc(it.label)}</b><small>${esc(classification(it))}${it.treat===false?' • não tratar nesta sessão':''}</small></div></div>`).join('')+'</div><button id="continueToTreatmentV3" type="button" class="primary wide">Continuar para tratamento</button>';$('#continueToTreatmentV3').addEventListener('click',startTreatment,{once:true})}

function activeTreatmentItems(){const ordered=orderedCausal();return ordered.filter(x=>x.treat!==false)}
function startTreatment(){show('treatmentView');renderTreatment()}
function newGraph(){return{name:'',quantity:'',unit:'minutos'}}
function renderTreatment(){const host=$('treatmentItems');host.innerHTML='';const items=causal.items.length?activeTreatmentItems():session.findings.map((tag,i)=>({id:`f_${i}`,tag,label:plan(tag).label,command:plan(tag).command,treat:true,priority:false,root:null}));treatmentRecords=items.map(it=>({id:it.id,tag:it.tag,label:it.label,command:it.command,classification:classification(it),graphs:[newGraph()],notes:''}));if(!treatmentRecords.length){host.innerHTML='<section class="card"><p class="muted">Nenhum item foi selecionado para tratamento nesta sessão.</p></section>';return}treatmentRecords.forEach((rec,i)=>{const card=document.createElement('section');card.className='card treatmentCard';card.innerHTML=`<span class="pill">${i+1} de ${treatmentRecords.length}</span><h3>${esc(rec.label)}</h3><p class="causalBadge">${esc(rec.classification)}</p><p class="fieldTitle">Comando sugerido</p><p class="command">${esc(rec.command)}</p><div class="graphs"></div><button type="button" class="ghost addGraph">+ Adicionar outro gráfico</button><div class="field"><label>Observações deste item</label><textarea class="itemNotes" placeholder="Percepções ou validações..."></textarea></div>`;const box=card.querySelector('.graphs');renderGraphRow(rec,box,0);card.querySelector('.addGraph').addEventListener('click',()=>{rec.graphs.push(newGraph());renderGraphRow(rec,box,rec.graphs.length-1)});card.querySelector('.itemNotes').addEventListener('input',e=>rec.notes=e.target.value);host.appendChild(card)})}
function renderGraphRow(rec,box,index){const g=rec.graphs[index],row=document.createElement('div');row.className='graphRow structuredTime';row.innerHTML=`<div class="field graphField"><label>Gráfico ${index+1}</label><input class="graphName" type="text" placeholder="Nome do gráfico" value="${esc(g.name)}"></div><div class="field durationField"><label>Tempo necessário</label><div class="durationInputs"><input class="graphQty" type="number" inputmode="numeric" min="0" step="1" placeholder="0" value="${esc(g.quantity)}"><select class="graphUnit" aria-label="Unidade de tempo"><option value="minutos">minutos</option><option value="horas">horas</option><option value="dias">dias</option><option value="semanas">semanas</option><option value="meses">meses</option></select></div></div>`;row.querySelector('.graphUnit').value=g.unit;row.querySelector('.graphName').addEventListener('input',e=>g.name=e.target.value);row.querySelector('.graphQty').addEventListener('input',e=>g.quantity=e.target.value);row.querySelector('.graphUnit').addEventListener('change',e=>g.unit=e.target.value);box.appendChild(row)}

function startPostValidation(){session.final=Number($('finalIntensity').value||0);session.generalNotes=$('notes').value||'';session.treatment=JSON.parse(JSON.stringify(treatmentRecords));const items=causal.items.filter(it=>it.treat!==false&&treatmentRecords.some(r=>r.id===it.id));if(!items.length)return finishReport();causal.phase='post';causal.postItems=items;causal.index=0;causal.step='neutralized';show('causalView');renderPost()}
function renderPost(){const it=causal.postItems[causal.index];if(!it)return finishReport();const ctx=`Achado tratado: ${it.label}`;if(causal.step==='neutralized')setCausalQuestion('Após o tratamento, este fator foi neutralizado suficientemente nesta sessão?',ctx);else setCausalQuestion('Este fator precisa de uma nova sessão específica de acompanhamento?',ctx)}
function answerPost(yes){const it=causal.postItems[causal.index];if(causal.step==='neutralized'){it.neutralized=yes;if(yes){it.followup=false;causal.index++;causal.step='neutralized'}else causal.step='followup'}else{it.followup=yes;causal.index++;causal.step='neutralized'}renderPost()}
const originalAnswerCausal=answerCausal;
answerCausal=function(yes){if(causal.phase==='post')return answerPost(yes);return originalAnswerCausal(yes)};
function postStatus(it){return it.neutralized===true?'Neutralizado suficientemente nesta sessão':it.neutralized===false?(it.followup?'Não neutralizado • acompanhamento indicado':'Não neutralizado'):'Não validado'}
function finishReport(){session.causal={items:causal.items,ordered:orderedCausal().map(x=>x.id)};saveSession();renderReport();show('reportView')}
function renderReport(){const body=$('reportBody');$('reportTitle').textContent=`${session.title} — relatório da sessão`;$('reportMeta').textContent=`${new Date(session.date).toLocaleString('pt-BR')} • ${session.initial}% → ${session.final}%`;body.innerHTML=`<section class="card metric"><div><span class="muted">Antes</span><strong>${session.initial}%</strong></div><div><span class="muted">Depois</span><strong>${session.final}%</strong></div></section>`;const sec=document.createElement('section');sec.className='card reportSection';sec.innerHTML='<h3>Tratamento realizado</h3>';session.treatment.forEach(r=>{const it=session.causal.items.find(x=>x.id===r.id),gs=(r.graphs||[]).filter(g=>g.name||g.quantity),d=document.createElement('div');d.className='reportTreatment';d.innerHTML=`<h4>${esc(r.label)}</h4><p><b>Classificação:</b> ${esc(classification(it||{}))}</p><p><b>Comando:</b> ${esc(r.command)}</p>`+(gs.length?'<ul>'+gs.map(g=>`<li><b>${esc(g.name||'Gráfico')}</b> — ${esc(unitLabel(g.quantity,g.unit)||'tempo não registrado')}</li>`).join('')+'</ul>':'<p class="muted">Nenhum gráfico registrado.</p>')+(r.notes?`<p><b>Observações:</b> ${esc(r.notes)}</p>`:'')+(it?`<p><b>Validação:</b> ${esc(postStatus(it))}</p>`:'');sec.appendChild(d)});body.appendChild(sec);if(session.generalNotes){const n=document.createElement('section');n.className='card reportSection';n.innerHTML=`<h3>Observações gerais</h3><p>${esc(session.generalNotes)}</p>`;body.appendChild(n)}}
function saveSession(){try{let h=JSON.parse(localStorage.getItem('rt_sessions_v3')||'[]');h.unshift(session);localStorage.setItem('rt_sessions_v3',JSON.stringify(h.slice(0,50)))}catch(e){console.error('Falha ao salvar sessão',e)}}

function renderHistory(){const box=$('historyList');box.innerHTML='';let v3=[],rich=[],legacy=[];try{v3=JSON.parse(localStorage.getItem('rt_sessions_v3')||'[]')}catch(e){}try{rich=JSON.parse(localStorage.getItem('rt_rich_sessions')||'[]')}catch(e){}try{legacy=JSON.parse(localStorage.getItem('rt_sessions_v2')||'[]')}catch(e){}if(!v3.length&&!rich.length&&!legacy.length){box.innerHTML='<p class="muted">Nenhuma sessão salva ainda.</p>';return}v3.forEach(s=>box.appendChild(historyCardV3(s)));rich.forEach(s=>box.appendChild(historyCardRich(s)));legacy.forEach(s=>box.appendChild(historyCardLegacy(s)))}
function historyCardV3(s){const d=document.createElement('details');d.className='historyCard';const recs=s.treatment||[];d.innerHTML=`<summary><span><b>${esc(s.title)}</b><small>${esc(new Date(s.date).toLocaleString('pt-BR'))} • ${s.initial}% → ${s.final}% • ${recs.length} tratados</small></span><span class="historyChevron">⌄</span></summary><div class="historyDetails">${recs.map(r=>{const it=s.causal?.items?.find(x=>x.id===r.id),gs=(r.graphs||[]).filter(g=>g.name||g.quantity);return `<div class="historyFinding"><b>${esc(r.label)}</b><p>${esc(r.command||'')}</p><p><b>Classificação:</b> ${esc(it?classification(it):r.classification||'')}</p>`+(gs.length?'<ul>'+gs.map(g=>`<li>${esc(g.name||'Gráfico')} — ${esc(unitLabel(g.quantity,g.unit)||g.time||'tempo não registrado')}</li>`).join('')+'</ul>':'<p class="muted">Sem gráfico registrado.</p>')+(r.notes?`<p><b>Observações:</b> ${esc(r.notes)}</p>`:'')+(it?`<p><b>Validação:</b> ${esc(postStatus(it))}</p>`:'')+'</div>'}).join('')}${s.generalNotes?`<div class="historyGeneral"><b>Observações gerais</b><p>${esc(s.generalNotes)}</p></div>`:''}</div>`;return d}
function historyCardRich(s){const d=document.createElement('details');d.className='historyCard legacy';d.innerHTML=`<summary><span><b>${esc(s.title||s.mode)}</b><small>${esc(new Date(s.date).toLocaleString('pt-BR'))} • sessão anterior</small></span><span class="historyChevron">⌄</span></summary><div class="historyDetails">${(s.records||[]).map(r=>`<div class="historyFinding"><b>${esc(r.label)}</b><p>${esc(r.command||'')}</p></div>`).join('')}<p class="muted historyNote">Sessão criada em versão anterior; alguns detalhes podem não estar disponíveis.</p></div>`;return d}
function historyCardLegacy(s){const d=document.createElement('details');d.className='historyCard legacy';d.innerHTML=`<summary><span><b>${esc(s.title||s.mode)}</b><small>${esc(new Date(s.date).toLocaleString('pt-BR'))} • sessão anterior</small></span><span class="historyChevron">⌄</span></summary><div class="historyDetails"><p class="muted">Registro criado em versão anterior do aplicativo.</p></div>`;return d}

function copyReport(){const text=$('reportView').innerText;if(navigator.clipboard?.writeText)navigator.clipboard.writeText(text).then(()=>{$('copyBtn').textContent='Copiado';setTimeout(()=>$('copyBtn').textContent='Copiar relatório',1200)})}
function bindCapture(el,event,fn){el?.addEventListener(event,e=>{e.preventDefault();e.stopImmediatePropagation();fn(e)},true)}
function install(){ensureCausalView();show('homeView');document.querySelectorAll('[data-open-mode]').forEach(b=>bindCapture(b,'click',()=>openProtocol(b.dataset.openMode)));document.querySelectorAll('.backHome').forEach(b=>bindCapture(b,'click',goHome));bindCapture($('headerHomeBtn'),'click',goHome);bindCapture($('startBtn'),'click',startInvestigation);document.querySelectorAll('[data-answer]').forEach(b=>bindCapture(b,'click',()=>answerInvestigation(b.dataset.answer)));bindCapture($('backBtn'),'click',backQuestion);bindCapture($('finishEarlyBtn'),'click',finishInvestigation);bindCapture($('toTreatmentBtn'),'click',startCausal);bindCapture($('makeReportBtn'),'click',startPostValidation);bindCapture($('historyBtn'),'click',()=>{renderHistory();show('historyView')});bindCapture($('closeHistory'),'click',goHome);bindCapture($('newBtn'),'click',goHome);bindCapture($('printBtn'),'click',()=>window.print());bindCapture($('copyBtn'),'click',copyReport);$('initialIntensity').addEventListener('input',e=>$('initialOut').textContent=`${e.target.value}%`);$('finalIntensity').addEventListener('input',e=>$('finalOut').textContent=`${e.target.value}%`)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();