(function(){
'use strict';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const singular={minutos:'minuto',horas:'hora',dias:'dia',semanas:'semana',meses:'mês'};
const duration=(q,u)=>{const n=Number(q);return n?`${n} ${n===1?(singular[u]||u):u}`:''};
let session=null,currentId=null,answeredOrder=[],investMax=0,causal=null,treatments=[];
const views=['homeView','startView','questionView','priorityView','treatmentView','reportView','historyView','causalView'];
function show(id){views.forEach(v=>$(v)?.classList.add('hidden'));$(id)?.classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}
function plan(tag){return PLANS[tag]||{label:tag||'Achado',command:'Investigar e formular um comando específico para este achado.'}}
function isQuick(){return (session?.kind||DATA[session?.mode]?.kind)==='quick'}
function resetUI(){if($('notes'))$('notes').value='';if($('initialIntensity'))$('initialIntensity').value=50;if($('initialOut'))$('initialOut').textContent='50%';if($('finalIntensity'))$('finalIntensity').value=20;if($('finalOut'))$('finalOut').textContent='20%';if($('treatmentItems'))$('treatmentItems').innerHTML='';if($('reportBody'))$('reportBody').innerHTML='';if($('priorityList'))$('priorityList').innerHTML='';const badge=document.querySelector('#startView .sectionLabel'),intro=document.querySelector('#startView .instruction.concise p'),start=$('startBtn');if(badge)badge.textContent='Nova sessão';if(intro)intro.innerHTML='Faça cada pergunta com o pêndulo e registre somente <b>Sim</b> ou <b>Não</b>. Quando necessário, o protocolo aprofundará a resposta em novas perguntas.';if(start)start.textContent='Começar investigação'}
function sanitizeTree(mode){const source=(DATA[mode]?.questions||[]).map(q=>({...q})),seen=new Set(),dedup=[];source.forEach(q=>{if(!q?.id||seen.has(q.id)){console.warn('Pergunta inválida/duplicada ignorada',q?.id);return}seen.add(q.id);dedup.push(q)});const ids=new Set(dedup.map(q=>q.id));dedup.forEach(q=>{if(q.parent&&!ids.has(q.parent)){console.warn('Pai inexistente; pergunta promovida a nível principal',q.id,q.parent);q.parent=null}if(q.parent===q.id){console.warn('Auto-referência removida',q.id);q.parent=null}if(q.tag&&!PLANS[q.tag])console.warn('Achado sem plano específico; fallback será usado',q.tag)});return dedup}
function qMap(){return new Map(session.questions.map(q=>[q.id,q]))}
function eligible(q){return !q.parent||session.answers[q.parent]==='yes'}
function descendants(id){const out=new Set();let changed=true;while(changed){changed=false;session.questions.forEach(q=>{if(q.parent&&(q.parent===id||out.has(q.parent))&&!out.has(q.id)){out.add(q.id);changed=true}})}return out}
function cleanAnswers(){const map=qMap();Object.keys(session.answers).forEach(id=>{const q=map.get(id);if(!q||!eligible(q)){delete session.answers[id];answeredOrder=answeredOrder.filter(x=>x!==id)}})}
function findings(){const seen=new Set();session.findings=[];session.questions.forEach(q=>{if(q.tag&&session.answers[q.id]==='yes'&&!seen.has(q.tag)){seen.add(q.tag);session.findings.push(q.tag)}})}
function nextQuestion(){cleanAnswers();return session.questions.find(q=>eligible(q)&&session.answers[q.id]===undefined)||null}
function investPct(){const e=session.questions.filter(eligible),done=e.filter(q=>session.answers[q.id]!==undefined).length;let p=e.length?Math.round(done/e.length*100):0;if(p<100)p=Math.min(96,p);investMax=Math.max(investMax,p);return investMax}
function setInvestPct(){const p=investPct();$('counter').textContent=`${p}%`;$('progressBar').style.width=`${p}%`;if($('backBtn'))$('backBtn').disabled=!answeredOrder.length}
function goHome(){session=null;currentId=null;answeredOrder=[];investMax=0;causal=null;treatments=[];resetUI();show('homeView')}
function openProtocol(mode){resetUI();document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.mode===mode));const data=DATA[mode];$('startTitle').textContent=data?.title||mode;if(data?.kind==='quick'){const badge=document.querySelector('#startView .sectionLabel'),intro=document.querySelector('#startView .instruction.concise p'),start=$('startBtn');if(badge)badge.textContent='Sessão rápida';if(intro)intro.innerHTML='Esta é uma sessão curta. Faça cada pergunta com o pêndulo e registre somente <b>Sim</b> ou <b>Não</b>. Ao final, você irá direto aos itens identificados para tratamento.';if(start)start.textContent='Começar sessão rápida'}show('startView')}
function startInvestigation(){const mode=document.querySelector('.tab.active')?.dataset.mode||'finance';session={id:Date.now(),date:new Date().toISOString(),mode,title:DATA[mode].title,kind:DATA[mode]?.kind||'deep',questions:sanitizeTree(mode),answers:{},findings:[],initial:Number($('initialIntensity').value||0),final:null,generalNotes:'',causal:null,treatment:[]};answeredOrder=[];investMax=0;const q=nextQuestion();if(!q)return finishInvestigation();currentId=q.id;show('questionView');renderQuestion()}
function renderQuestion(){const q=qMap().get(currentId);if(!q)return finishInvestigation();$('sectionPill').textContent=q.section||'Investigação';$('question').textContent=q.q;setInvestPct()}
function answerInvestigation(value){const q=qMap().get(currentId);if(!q)return;session.answers[q.id]=value;if(!answeredOrder.includes(q.id))answeredOrder.push(q.id);if(value==='no'){const ds=descendants(q.id);ds.forEach(id=>delete session.answers[id]);answeredOrder=answeredOrder.filter(id=>!ds.has(id))}findings();const next=nextQuestion();if(next){currentId=next.id;renderQuestion()}else finishInvestigation()}
function backInvestigation(){if(!answeredOrder.length)return;const id=answeredOrder.pop(),ds=descendants(id);delete session.answers[id];ds.forEach(x=>delete session.answers[x]);answeredOrder=answeredOrder.filter(x=>!ds.has(x));findings();currentId=id;investMax=Math.max(0,investMax-3);renderQuestion()}
function finishInvestigation(){findings();const host=$('priorityList');host.innerHTML='';if(!session.findings.length)host.innerHTML='<p class="muted">Nenhum item específico foi identificado nos ramos respondidos.</p>';else session.findings.forEach(tag=>{const p=plan(tag),d=document.createElement('div');d.className='check';d.dataset.tag=tag;d.innerHTML=`<b>${esc(p.label)}</b><small><strong>Comando sugerido:</strong> ${esc(p.command)}</small>`;host.appendChild(d)});const badge=$('priorityView')?.querySelector('.pill'),title=$('priorityView')?.querySelector('h2'),copy=$('priorityView')?.querySelector('.muted'),btn=$('toTreatmentBtn');if(isQuick()){if(badge)badge.textContent='Sessão rápida concluída';if(title)title.textContent='O que será trabalhado';if(copy)copy.textContent='Revise os itens identificados. Como esta é uma sessão rápida, não faremos a investigação causal extensa antes do tratamento.';if(btn)btn.textContent='Continuar para tratamento'}else{if(badge)badge.textContent='Investigação concluída';if(title)title.textContent='O que precisa ser tratado';if(copy)copy.textContent='Revise os achados antes de validar a causalidade e a ordem de tratamento.';if(btn)btn.textContent='Validar causalidade e ordem'}show('priorityView')}
function ensureCausalView(){if($('causalView'))return;const s=document.createElement('section');s.id='causalView';s.className='card hidden';s.innerHTML='<div class="questionTop"><span class="pill">Validação causal</span><span id="causalPercent" class="muted">0%</span></div><div class="progress"><span id="causalProgress"></span></div><p class="microInstruction">Consulte o pêndulo</p><h2 id="causalTitle"></h2><p id="causalContext" class="muted"></p><div id="causalAnswers" class="answerGrid"><button class="answer yes" data-causal="yes">Sim</button><button class="answer no" data-causal="no">Não</button></div><div id="causalPlan" class="hidden"></div>';document.querySelector('main').appendChild(s);s.querySelectorAll('[data-causal]').forEach(b=>b.addEventListener('click',()=>answerCausal(b.dataset.causal==='yes')))}
function causalItem(tag,i){const p=plan(tag);return{id:`f_${i}`,tag,label:p.label,command:p.command,root:null,priorCause:null,priorIdentified:null,origin:null,deepenPrior:null,treat:null,priority:null,neutralized:null,followup:null}}
function startQuickTreatment(){causal={phase:'quick',index:0,step:null,items:session.findings.map(causalItem),postItems:[]};causal.items.forEach(it=>{it.quick=true;it.treat=true});session.causal={items:causal.items,ordered:causal.items.map(x=>x.id)};startTreatment()}
function startCausal(){ensureCausalView();causal={phase:'pre',index:0,step:'root',items:session.findings.map(causalItem),postItems:[]};if(!causal.items.length)return startTreatment();show('causalView');renderCausal()}
const stepRank={root:0,prior:1,identified:2,originInternal:3,originExternal:3.5,originFamily:4,originSpiritual:4.5,deepen:5,treat:6,priority:7};
function causalPct(){if(!causal?.items?.length)return 100;const r=stepRank[causal.step]??0;return Math.min(99,Math.round((causal.index+r/8)/causal.items.length*100))}
function setCausalQ(title,ctx,p=causalPct()){$('causalTitle').textContent=title;$('causalContext').textContent=ctx||'';$('causalPercent').textContent=`${p}%`;$('causalProgress').style.width=`${p}%`;$('causalAnswers').classList.remove('hidden');$('causalPlan').classList.add('hidden')}
function renderCausal(){const it=causal.items[causal.index];if(!it)return showCausalPlan();const ctx=`Achado: ${it.label}`;const text={root:'Este achado é uma causa raiz ativa, e não apenas uma consequência?',prior:'Há uma causa anterior a este achado que precisa ser considerada?',identified:'Essa causa anterior já foi identificada em outro ramo desta investigação?',originInternal:'A causa anterior parece ser predominantemente interna?',originExternal:'A causa anterior parece ser predominantemente externa?',originFamily:'A causa anterior parece ser familiar, ancestral ou transgeracional?',originSpiritual:'Dentro da sua prática, a causa anterior parece ser espiritual, simbólica ou energética?',deepen:'Essa causa anterior precisa ser aprofundada antes de tratar este achado?',treat:'Este achado deve ser tratado nesta sessão?',priority:'Este achado precisa ser tratado antes dos demais itens identificados?'};setCausalQ(text[causal.step],ctx)}
function nextCausal(){causal.index++;causal.step='root';renderCausal()}
function answerPre(yes){const it=causal.items[causal.index];switch(causal.step){case'root':it.root=yes;causal.step=yes?'treat':'prior';break;case'prior':it.priorCause=yes;causal.step=yes?'identified':'treat';break;case'identified':it.priorIdentified=yes;causal.step=yes?'treat':'originInternal';break;case'originInternal':if(yes){it.origin='Interna';causal.step='deepen'}else causal.step='originExternal';break;case'originExternal':if(yes){it.origin='Externa';causal.step='deepen'}else causal.step='originFamily';break;case'originFamily':if(yes){it.origin='Familiar / ancestral';causal.step='deepen'}else causal.step='originSpiritual';break;case'originSpiritual':it.origin=yes?'Espiritual / simbólica':'Não delimitada';causal.step='deepen';break;case'deepen':it.deepenPrior=yes;causal.step='treat';break;case'treat':it.treat=yes;if(yes)causal.step='priority';else return nextCausal();break;case'priority':it.priority=yes;return nextCausal()}renderCausal()}
function classification(it){if(!it)return'';if(it.quick===true)return'Foco da sessão rápida';if(it.root===true)return it.priority?'Causa raiz • prioridade':'Causa raiz';if(it.priorCause===true){let s=it.priorIdentified?'Consequência de causa anterior identificada':'Consequência de causa anterior';if(it.origin)s+=` • origem ${it.origin.toLowerCase()}`;if(it.deepenPrior)s+=' • aprofundar antes';return s}return'Fator associado / intermediário'}
function ordered(){return(causal?.items||[]).slice().sort((a,b)=>Number(b.treat===true)-Number(a.treat===true)||Number(b.priority===true)-Number(a.priority===true)||Number(b.root===true)-Number(a.root===true))}
function showCausalPlan(){session.causal={items:causal.items,ordered:ordered().map(x=>x.id)};$('causalPercent').textContent='100%';$('causalProgress').style.width='100%';$('causalTitle').textContent='Ordem de tratamento';$('causalContext').textContent='Revise a classificação antes de continuar.';$('causalAnswers').classList.add('hidden');const h=$('causalPlan');h.classList.remove('hidden');h.innerHTML='<div class="causalPlanList">'+ordered().map((it,i)=>`<div class="causalPlanItem"><span class="pill">${i+1}</span><div><b>${esc(it.label)}</b><small>${esc(classification(it))}${it.treat===false?' • não tratar nesta sessão':''}</small></div></div>`).join('')+'</div><button id="continueTreatment" type="button" class="primary wide">Continuar para tratamento</button>';const b=$('continueTreatment');b.disabled=false;b.addEventListener('click',startTreatment,{once:true})}
function graph(){return{name:'',quantity:'',unit:'minutos'}}
function startTreatment(){show('treatmentView');const source=causal?.items?.length?ordered().filter(x=>x.treat!==false):session.findings.map(causalItem);treatments=source.map(it=>({id:it.id,tag:it.tag,label:it.label,command:it.command,classification:classification(it),graphs:[graph()],notes:''}));renderTreatment()}
function renderTreatment(){const host=$('treatmentItems');host.innerHTML='';if(!treatments.length){host.innerHTML='<section class="card"><p class="muted">Nenhum item foi selecionado para tratamento nesta sessão.</p></section>';return}treatments.forEach((r,i)=>{const c=document.createElement('section');c.className='card treatmentCard';c.innerHTML=`<span class="pill">${i+1} de ${treatments.length}</span><h3>${esc(r.label)}</h3><p class="causalBadge">${esc(r.classification)}</p><p class="fieldTitle">Comando sugerido</p><p class="command">${esc(r.command)}</p><div class="graphs"></div><button type="button" class="ghost addGraph">+ Adicionar outro gráfico</button><div class="field"><label>Observações deste item</label><textarea class="itemNotes" placeholder="Percepções ou validações..."></textarea></div>`;const box=c.querySelector('.graphs');renderGraph(r,box,0);c.querySelector('.addGraph').onclick=()=>{r.graphs.push(graph());renderGraph(r,box,r.graphs.length-1)};c.querySelector('.itemNotes').oninput=e=>r.notes=e.target.value;host.appendChild(c)})}
function renderGraph(r,box,i){const g=r.graphs[i],row=document.createElement('div');row.className='graphRow structuredTime';row.innerHTML=`<div class="field"><label>Gráfico ${i+1}</label><input class="graphName" type="text" placeholder="Nome do gráfico"></div><div class="field"><label>Tempo necessário</label><div class="durationInputs"><input class="graphQty" type="number" inputmode="numeric" min="0" step="1" placeholder="0"><select class="graphUnit"><option value="minutos">minutos</option><option value="horas">horas</option><option value="dias">dias</option><option value="semanas">semanas</option><option value="meses">meses</option></select></div></div>`;row.querySelector('.graphUnit').value=g.unit;row.querySelector('.graphName').oninput=e=>g.name=e.target.value;row.querySelector('.graphQty').oninput=e=>g.quantity=e.target.value;row.querySelector('.graphUnit').onchange=e=>g.unit=e.target.value;box.appendChild(row)}
function startPost(){session.final=Number($('finalIntensity').value||0);session.generalNotes=$('notes').value||'';session.treatment=JSON.parse(JSON.stringify(treatments));const items=(causal?.items||[]).filter(it=>it.treat!==false&&treatments.some(r=>r.id===it.id));if(!items.length)return finishReport();causal.phase='post';causal.postItems=items;causal.index=0;causal.step='neutralized';show('causalView');renderPost()}
function postPct(){const n=causal.postItems.length,i=causal.index,half=causal.step==='followup'?.5:0;return Math.min(99,Math.round((i+half)/n*100))}
function renderPost(){const it=causal.postItems[causal.index];if(!it)return finishReport();const title=causal.step==='neutralized'?'Após o tratamento, este fator foi neutralizado suficientemente nesta sessão?':'Este fator precisa de uma nova sessão específica de acompanhamento?';setCausalQ(title,`Achado tratado: ${it.label}`,postPct())}
function answerPost(yes){const it=causal.postItems[causal.index];if(causal.step==='neutralized'){it.neutralized=yes;if(yes){it.followup=false;causal.index++;causal.step='neutralized'}else causal.step='followup'}else{it.followup=yes;causal.index++;causal.step='neutralized'}renderPost()}
function answerCausal(yes){if(causal.phase==='post')answerPost(yes);else answerPre(yes)}
function postStatus(it){return it?.neutralized===true?'Neutralizado suficientemente nesta sessão':it?.neutralized===false?(it.followup?'Não neutralizado • acompanhamento indicado':'Não neutralizado'):'Não validado'}
function persistable(){return{id:session.id,date:session.date,mode:session.mode,title:session.title,kind:session.kind,initial:session.initial,final:session.final,generalNotes:session.generalNotes,answers:session.answers,findings:session.findings,causal:session.causal,treatment:session.treatment}}
function save(){try{let h=JSON.parse(localStorage.getItem('rt_sessions_v4')||'[]');h.unshift(persistable());localStorage.setItem('rt_sessions_v4',JSON.stringify(h.slice(0,50)))}catch(e){console.error('Não foi possível salvar a sessão',e)}}
function finishReport(){session.causal={items:causal?.items||[],ordered:ordered().map(x=>x.id)};save();renderReport();show('reportView')}
function renderReport(){const body=$('reportBody');$('reportTitle').textContent=`${session.title} — relatório da sessão`;$('reportMeta').textContent=`${new Date(session.date).toLocaleString('pt-BR')} • ${session.initial}% → ${session.final}%`;body.innerHTML=`<section class="card metric"><div><span class="muted">Antes</span><strong>${session.initial}%</strong></div><div><span class="muted">Depois</span><strong>${session.final}%</strong></div></section>`;const sec=document.createElement('section');sec.className='card reportSection';sec.innerHTML='<h3>Tratamento realizado</h3>';session.treatment.forEach(r=>{const it=session.causal.items.find(x=>x.id===r.id),gs=(r.graphs||[]).filter(g=>g.name||g.quantity),d=document.createElement('div');d.className='reportTreatment';d.innerHTML=`<h4>${esc(r.label)}</h4><p><b>Classificação:</b> ${esc(classification(it)||r.classification)}</p><p><b>Comando:</b> ${esc(r.command)}</p>`+(gs.length?'<ul>'+gs.map(g=>`<li><b>${esc(g.name||'Gráfico')}</b> — ${esc(duration(g.quantity,g.unit)||'tempo não registrado')}</li>`).join('')+'</ul>':'<p class="muted">Nenhum gráfico registrado.</p>')+(r.notes?`<p><b>Observações:</b> ${esc(r.notes)}</p>`:'')+(it?`<p><b>Validação:</b> ${esc(postStatus(it))}</p>`:'');sec.appendChild(d)});body.appendChild(sec);if(session.generalNotes){const n=document.createElement('section');n.className='card reportSection';n.innerHTML=`<h3>Observações gerais</h3><p>${esc(session.generalNotes)}</p>`;body.appendChild(n)}}
function load(key){try{return JSON.parse(localStorage.getItem(key)||'[]')}catch(e){return[]}}
function historyV4(s){const d=document.createElement('details');d.className='historyCard';d.innerHTML=`<summary><span><b>${esc(s.title)}</b><small>${esc(new Date(s.date).toLocaleString('pt-BR'))} • ${s.initial}% → ${s.final}% • ${(s.treatment||[]).length} tratados</small></span><span class="historyChevron">⌄</span></summary><div class="historyDetails">${(s.treatment||[]).map(r=>{const it=s.causal?.items?.find(x=>x.id===r.id),gs=(r.graphs||[]).filter(g=>g.name||g.quantity);return `<div class="historyFinding"><b>${esc(r.label)}</b><p>${esc(r.command||'')}</p><p><b>Classificação:</b> ${esc(classification(it)||r.classification||'')}</p>`+(gs.length?'<ul>'+gs.map(g=>`<li>${esc(g.name||'Gráfico')} — ${esc(duration(g.quantity,g.unit)||g.time||'tempo não registrado')}</li>`).join('')+'</ul>':'<p class="muted">Sem gráfico registrado.</p>')+(r.notes?`<p><b>Observações:</b> ${esc(r.notes)}</p>`:'')+(it?`<p><b>Validação:</b> ${esc(postStatus(it))}</p>`:'')+'</div>'}).join('')}${s.generalNotes?`<div class="historyGeneral"><b>Observações gerais</b><p>${esc(s.generalNotes)}</p></div>`:''}</div>`;return d}
function historyOld(s){const d=document.createElement('details');d.className='historyCard legacy';d.innerHTML=`<summary><span><b>${esc(s.title||s.mode||'Sessão anterior')}</b><small>${s.date?esc(new Date(s.date).toLocaleString('pt-BR')):''} • versão anterior</small></span><span class="historyChevron">⌄</span></summary><div class="historyDetails"><p class="muted">Registro criado em uma versão anterior; alguns detalhes podem não ter sido armazenados.</p></div>`;return d}
function renderHistory(){const box=$('historyList');box.innerHTML='';const modern=load('rt_sessions_v4'),older=[...load('rt_sessions_v3'),...load('rt_rich_sessions'),...load('rt_sessions_v2')];if(!modern.length&&!older.length){box.innerHTML='<p class="muted">Nenhuma sessão salva ainda.</p>';return}modern.forEach(s=>box.appendChild(historyV4(s)));older.forEach(s=>box.appendChild(historyOld(s)))}
function copy(){const text=$('reportView').innerText;navigator.clipboard?.writeText(text).then(()=>{$('copyBtn').textContent='Copiado';setTimeout(()=>$('copyBtn').textContent='Copiar relatório',1200)})}
function bind(el,fn){el?.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();fn()},true)}
function install(){ensureCausalView();resetUI();show('homeView');document.querySelectorAll('[data-open-mode]').forEach(b=>bind(b,()=>openProtocol(b.dataset.openMode)));document.querySelectorAll('.backHome').forEach(b=>bind(b,goHome));bind($('headerHomeBtn'),goHome);bind($('startBtn'),startInvestigation);document.querySelectorAll('[data-answer]').forEach(b=>bind(b,()=>answerInvestigation(b.dataset.answer)));bind($('backBtn'),backInvestigation);bind($('finishEarlyBtn'),finishInvestigation);bind($('toTreatmentBtn'),()=>isQuick()?startQuickTreatment():startCausal());bind($('makeReportBtn'),startPost);bind($('historyBtn'),()=>{renderHistory();show('historyView')});bind($('closeHistory'),goHome);bind($('newBtn'),goHome);bind($('printBtn'),()=>window.print());bind($('copyBtn'),copy);$('initialIntensity').addEventListener('input',e=>$('initialOut').textContent=`${e.target.value}%`);$('finalIntensity').addEventListener('input',e=>$('finalOut').textContent=`${e.target.value}%`)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();