(function(){
'use strict';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const STORE='rt_divorce_sessions_v1';
const STEPS=['Sessão','Ancoragem','Áreas','Tratamento geral','Corte geral','Reavaliação','Tratamentos específicos','Conclusão'];
const UNITS=['minutos','horas','dias','semanas','meses'];
const THEMES=['Relacionamentos amorosos','Ex-relacionamentos e prosperidade','Dependência emocional','Contratos, votos e promessas','Memórias sexuais','Lealdades ancestrais no amor','Culpa','Relações familiares','Sócios, clientes e parcerias','Ambientes e locais antigos','Escassez','Antiga versão / identidade','Medo de prosperar sozinha','Autossabotagem financeira','Dependência financeira emocional','Rejeição','Abandono','Traição','Humilhação e vergonha','Raiva reprimida','Pactos espirituais','Cordões drenantes','Interferências espirituais percebidas','Registros antigos / vidas passadas','Outro'];
const AREAS=[
{id:'affective',label:'Relacionamento afetivo',graph:'HRIM',group:'Relações'},
{id:'prosperity',label:'Prosperidade / financeiro',graph:'SRIM',group:'Recursos'},
{id:'health',label:'Saúde física',graph:'SHIN',group:'Corpo'},
{id:'professional',label:'Profissional',graph:'SRIM',group:'Recursos'},
{id:'environment',label:'Ambiente',graph:'KRIM',group:'Ambiente'},
{id:'trauma',label:'Trauma emocional',graph:'YOSHUA',group:'Emocional'},
{id:'negative',label:'Sentimentos negativos',graph:'YOSHUA',group:'Emocional'},
{id:'family',label:'Laço familiar',graph:'HRIM',group:'Relações'},
{id:'friendship',label:'Amizade',graph:'HRIM',group:'Relações'},
{id:'partnership',label:'Parceria profissional / sociedade',graph:'SRIM',group:'Recursos'},
{id:'past',label:'Experiência de vida passada / registro antigo',graph:'72 NOMES DE DEUS',group:'Espiritual / simbólico'},
{id:'belief',label:'Crença limitante',graph:'KRIM',group:'Padrões'},
{id:'selfdestructive',label:'Vício / padrão autodestrutivo',graph:'KRIM',group:'Padrões'},
{id:'spiritual',label:'Influência espiritual externa percebida',graph:'72 NOMES DE DEUS',group:'Espiritual / simbólico'},
{id:'grief',label:'Luto / falecido',graph:'72 NOMES DE DEUS',group:'Espiritual / simbólico'},
{id:'other',label:'Outro',graph:'KRIM',group:'Outro'}
];
const COMMANDS={
affective:'Dentro desta prática, trabalhar e liberar vínculos, promessas, dependências e memórias emocionais percebidas como limitantes no campo afetivo, preservando aprendizados e autonomia.',
prosperity:'Dentro desta prática, trabalhar vínculos percebidos com escassez, medo de receber, dependência ou experiências passadas que estejam associadas à prosperidade e ao fluxo financeiro.',
health:'Dentro desta prática, trabalhar somente os vínculos simbólicos ou energéticos percebidos como associados ao desconforto físico, sem substituir diagnóstico, tratamento ou acompanhamento de saúde.',
professional:'Dentro desta prática, trabalhar vínculos percebidos com experiências profissionais, contratos, frustrações, medos e padrões que estejam associados à limitação do desenvolvimento profissional.',
environment:'Dentro desta prática, trabalhar vínculos percebidos com ambientes ou locais antigos e liberar associações simbólicas que já não servem, mantendo atenção às causas concretas do ambiente.',
trauma:'Dentro desta prática, trabalhar vínculos percebidos com experiências emocionais passadas, preservando a segurança e reconhecendo que traumas podem exigir acompanhamento profissional adequado.',
negative:'Dentro desta prática, trabalhar vínculos percebidos com raiva, mágoa, culpa, tristeza ou ressentimento, favorecendo centramento e escolhas conscientes.',
family:'Dentro desta prática, trabalhar padrões, lealdades, promessas e vínculos familiares percebidos como limitantes, preservando pertencimento sem manter padrões prejudiciais.',
friendship:'Dentro desta prática, trabalhar vínculos e expectativas percebidas como limitantes em amizades, fortalecendo limites, autonomia e relações equilibradas.',
partnership:'Dentro desta prática, trabalhar vínculos percebidos com sociedades, clientes ou parcerias profissionais encerradas ou difíceis, preservando aprendizados e limites claros.',
past:'Dentro do sistema de crenças da pessoa, trabalhar registros antigos ou interpretações de vidas passadas percebidos como associados ao padrão atual, sem tratá-los como fatos verificáveis.',
belief:'Identificar e ressignificar crenças limitantes associadas ao vínculo investigado, fortalecendo interpretações e escolhas mais funcionais no presente.',
selfdestructive:'Identificar padrões autodestrutivos associados ao vínculo investigado e fortalecer estratégias concretas e seguras para interromper sua repetição.',
spiritual:'Dentro do sistema de crenças da pessoa, trabalhar influências espirituais ou energéticas percebidas como externas, reforçando limites e centramento sem apresentá-las como fatos objetivos.',
grief:'Dentro do sistema de crenças da pessoa, trabalhar simbolicamente vínculos associados ao luto ou à pessoa falecida, preservando memória e afeto enquanto se apoia o processo de seguir adiante.',
other:'Trabalhar o vínculo específico identificado pelo pêndulo, formulando um comando claro, ético e coerente com a situação e com os limites da prática.'
};
let s=null,step=0;
function blankPerson(){return{name:'',birthDate:''}}
function blank(){return{id:Date.now(),createdAt:new Date().toISOString(),status:'draft',sessionType:'individual',sessionDate:new Date().toISOString().slice(0,10),people:[blankPerson()],theme:'',themeOther:'',intention:'',anchoring:{egregore:false,pendulum:false,intention:false},initial:Object.fromEntries(AREAS.map(a=>[a.id,null])),general:{graph:'KRIM',command:'Realizar um tratamento geral de divórcio energético dentro da prática, liberando vínculos percebidos como negativos ou limitantes e preservando apenas aprendizados e conexões saudáveis.',quantity:'',unit:'minutos',done:false},cut:{graph:'72 NOMES DE DEUS',command:'Realizar o corte geral dos vínculos ainda percebidos como limitantes dentro da prática, com intenção de encerramento, proteção e reintegração do que pertence a cada parte.',quantity:'',unit:'minutos',done:false},rescan:{},specific:{},finalized:null,followup:'',notes:'',completedAt:null}}
function load(){try{return JSON.parse(localStorage.getItem(STORE)||'[]')}catch(e){return[]}}
function saveAll(arr){try{localStorage.setItem(STORE,JSON.stringify(arr.slice(0,100)))}catch(e){console.error('Falha ao salvar Divórcio Energético',e)}}
function persist(){if(!s)return;const arr=load(),i=arr.findIndex(x=>x.id===s.id);if(i>=0)arr[i]=JSON.parse(JSON.stringify(s));else arr.unshift(JSON.parse(JSON.stringify(s)));saveAll(arr)}
function hideAll(){['homeView','startView','questionView','priorityView','treatmentView','reportView','historyView','causalView','assessmentView','reevalView','divorceView'].forEach(id=>$(id)?.classList.add('hidden'))}
function show(){hideAll();$('divorceView')?.classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}
function home(){persist();hideAll();$('homeView')?.classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}
function duration(g){const q=Number(g?.quantity||0);return q?`${q} ${q===1?({minutos:'minuto',horas:'hora',dias:'dia',semanas:'semana',meses:'mês'}[g.unit]||g.unit):g.unit}`:'tempo não registrado'}
function ensureUI(){
 if(!$('divorceView')){const el=document.createElement('section');el.id='divorceView';el.className='hidden';document.querySelector('main')?.appendChild(el)}
 if(!document.querySelector('.divorceLauncher')){const anchor=document.querySelector('#homeView .homeDivider')||document.querySelector('#homeView .homeSection');const box=document.createElement('section');box.className='divorceLauncher';box.innerHTML='<div class="divorceLauncherTop"><span class="divorceLauncherIcon">↯</span><div><h2>Divórcio Energético</h2><p>Fluxo guiado para sessão individual ou coletiva: identificar áreas, fazer tratamento geral, reavaliar e registrar tratamentos específicos.</p></div></div><div class="divorceLauncherActions"><button id="openDivorceBtn" class="primary wide" type="button">Iniciar Divórcio Energético</button></div>';anchor?.before(box)}
 $('openDivorceBtn')?.addEventListener('click',start);
 const observer=new MutationObserver(()=>{if($('historyView')&&!$('historyView').classList.contains('hidden'))setTimeout(appendHistory,20)});if($('historyView'))observer.observe($('historyView'),{attributes:true,attributeFilter:['class']});
}
function start(){s=blank();step=0;persist();render()}
function shell(title,copy,body,next='Continuar'){const pct=Math.round(step/(STEPS.length-1)*100);return `<div class="divorceShell"><div class="divorceCard"><div class="divorceSteps">${STEPS.map((x,i)=>`<span class="${i===step?'active':''}">${i+1} ${esc(x)}</span>`).join('')}</div><div class="divorceTop"><span class="pill">Divórcio Energético</span><span class="muted">${pct}%</span></div><div class="progress"><span style="width:${pct}%"></span></div><div class="divorceHeader"><h2>${esc(title)}</h2><p>${copy}</p></div>${body}<div class="divorceActions noPrint"><button id="divBack" class="ghost" type="button">${step===0?'Cancelar':'Voltar'}</button><button id="divNext" class="primary" type="button">${next}</button></div></div></div>`}
function render(){show();const host=$('divorceView');if(!host||!s)return;const r=[renderSetup,renderAnchor,renderAreas,renderGeneral,renderCut,renderRescan,renderSpecific,renderFinish][step];host.innerHTML=r();bind()}
function personRow(p,i){return `<div class="divorcePerson"><div><label>Nome</label><input data-person-name="${i}" value="${esc(p.name)}" placeholder="Nome"></div><div class="birth"><label>Nascimento</label><input data-person-birth="${i}" type="date" value="${esc(p.birthDate)}"></div>${s.people.length>1?`<button class="divorceRemove" type="button" data-remove-person="${i}" aria-label="Remover participante">×</button>`:'<span></span>'}</div>`}
function renderSetup(){return shell('Dados da sessão','Defina se o trabalho será individual ou coletivo e registre quem participa.','<div class="divorceField"><label>Tipo de sessão</label><div class="divorceChoices"><button class="divorceChoice '+(s.sessionType==='individual'?'selected':'')+'" data-session-type="individual">Individual</button><button class="divorceChoice '+(s.sessionType==='collective'?'selected':'')+'" data-session-type="collective">Coletiva</button></div></div><div class="divorceField"><label>Data</label><input id="divDate" type="date" value="'+esc(s.sessionDate)+'"></div><div class="divorceField"><label>'+(s.sessionType==='collective'?'Participantes':'Pessoa')+'</label><div class="divorceParticipants">'+s.people.map(personRow).join('')+'</div><button id="addDivPerson" type="button" class="ghost wide" style="margin-top:10px">+ Adicionar pessoa</button></div>'+(s.sessionType==='collective'?'<div class="divorceBulk"><div class="divorceField"><label>Colar lista de participantes</label><textarea id="divBulk" placeholder="Maria Silva — 12/05/1980\nJoão Souza — 03/11/1975"></textarea></div><button id="importDivBulk" type="button" class="ghost wide">Importar lista</button></div>':'')+'<div class="divorceField"><label>Tema principal <span class="optional">opcional</span></label><div class="divorceThemes">'+THEMES.map(t=>`<button type="button" class="divorceTheme ${s.theme===t?'selected':''}" data-theme="${esc(t)}">${esc(t)}</button>`).join('')+'</div></div>'+(s.theme==='Outro'?'<div class="divorceField"><label>Descreva o tema</label><input id="divThemeOther" value="'+esc(s.themeOther)+'"></div>':'')+'<div class="divorceField"><label>Intenção da sessão <span class="optional">opcional</span></label><textarea id="divIntention" placeholder="O que deseja trabalhar ou encerrar nesta sessão?">'+esc(s.intention)+'</textarea></div>')}
function renderAnchor(){return shell('Ancoragem e prontidão','O material de referência começa pela ancoragem. Use estes itens como apoio dentro da sua prática antes de iniciar a leitura das áreas.','<div class="divorceNotice">Esta é uma ferramenta de organização da prática radiestésica. Elementos espirituais ou energéticos são registrados como parte do sistema de crenças da pessoa, não como fatos objetivos.</div>'+[['egregore','Ancoragem / conexão definida para a sessão'],['pendulum','Pêndulo conferido e resposta neutra verificada'],['intention','Intenção da sessão clara e registrada']].map(([k,t])=>`<label class="divorceCheck"><input type="checkbox" data-anchor="${k}" ${s.anchoring[k]?'checked':''}><span>${esc(t)}</span></label>`).join(''))}
function areaCard(a,source){const v=source[a.id];return `<div class="divorceArea"><div class="divorceAreaTop"><div><strong>${esc(a.label)}</strong><small class="muted" style="display:block;margin-top:4px">${esc(a.group)}</small></div><div class="divorceBinary"><button type="button" data-area="${a.id}" data-value="yes" class="${v===true?'selected':''}">Sim</button><button type="button" data-area="${a.id}" data-value="no" class="${v===false?'selected':''}">Não</button></div></div></div>`}
function renderAreas(){return shell('Quais áreas precisam passar pelo Divórcio Energético?','Consulte o pêndulo para cada área e registre Sim ou Não. O aplicativo manterá os itens positivos para o tratamento e para a reavaliação posterior.','<div class="divorceAreaList">'+AREAS.map(a=>areaCard(a,s.initial)).join('')+'</div>')}
function treatmentFields(obj,prefix){return `<div class="divorceField"><label>Gráfico</label><input id="${prefix}Graph" value="${esc(obj.graph)}"></div><div class="divorceField"><label>Comando de trabalho</label><textarea id="${prefix}Command">${esc(obj.command)}</textarea></div><div class="divorceField"><label>Tempo indicado</label><div class="divorceDuration"><input id="${prefix}Qty" type="number" min="0" step="1" inputmode="numeric" placeholder="Quantidade" value="${esc(obj.quantity)}"><select id="${prefix}Unit">${UNITS.map(u=>`<option ${obj.unit===u?'selected':''}>${u}</option>`).join('')}</select></div></div><label class="divorceCheck"><input id="${prefix}Done" type="checkbox" ${obj.done?'checked':''}><span>Tratamento realizado nesta sessão</span></label>`}
function renderGeneral(){const yes=AREAS.filter(a=>s.initial[a.id]===true);return shell('Tratamento geral — KRIM','Após identificar as áreas, o material utiliza KRIM como gráfico geral antes do corte e da nova aferição.','<div class="divorceNotice"><strong>Áreas inicialmente marcadas:</strong> '+(yes.length?yes.map(x=>esc(x.label)).join(' • '):'nenhuma área marcada')+'</div>'+treatmentFields(s.general,'general'))}
function renderCut(){return shell('Corte geral','Registre a etapa de corte geral antes de pendular novamente as áreas. O material de referência associa esta etapa ao gráfico 72 Nomes de Deus.','<div class="divorceNotice">Confirme com seu pêndulo e com sua metodologia se este gráfico é adequado para a sessão. Você pode alterar o gráfico abaixo.</div>'+treatmentFields(s.cut,'cut'))}
function renderRescan(){const yes=AREAS.filter(a=>s.initial[a.id]===true);return shell('Pendule novamente as áreas','Reavalie somente aquilo que havia sido identificado antes do tratamento geral. Os itens que continuarem em Sim seguirão para tratamento específico.','<div class="divorceAreaList">'+(yes.length?yes.map(a=>areaCard(a,s.rescan)).join(''):'<div class="divorceNotice">Nenhuma área havia sido marcada na primeira aferição.</div>')+'</div>')}
function ensureSpecific(){AREAS.filter(a=>s.rescan[a.id]===true).forEach(a=>{if(!s.specific[a.id])s.specific[a.id]={graph:a.graph,command:COMMANDS[a.id],quantity:'',unit:'minutos',done:false}})}
function specificBlock(a){const o=s.specific[a.id];return `<div class="divorceTreatment"><h3>${esc(a.label)}</h3><span class="divorceGraphHint">Gráfico sugerido no material: ${esc(a.graph)}</span><div class="divorceField"><label>Gráfico utilizado</label><input data-specific-graph="${a.id}" value="${esc(o.graph)}"></div><div class="divorceField"><label>Comando</label><textarea data-specific-command="${a.id}">${esc(o.command)}</textarea></div><div class="divorceField"><label>Tempo indicado</label><div class="divorceDuration"><input data-specific-qty="${a.id}" type="number" min="0" step="1" inputmode="numeric" placeholder="Quantidade" value="${esc(o.quantity)}"><select data-specific-unit="${a.id}">${UNITS.map(u=>`<option ${o.unit===u?'selected':''}>${u}</option>`).join('')}</select></div></div><label class="divorceCheck"><input type="checkbox" data-specific-done="${a.id}" ${o.done?'checked':''}><span>Tratamento específico realizado</span></label></div>`}
function renderSpecific(){ensureSpecific();const remain=AREAS.filter(a=>s.rescan[a.id]===true);return shell('Tratamentos específicos','Para cada área que permaneceu ativa após o tratamento geral, registre o gráfico, o comando e o tempo indicado. As sugestões de gráfico vêm do material de referência e podem ser alteradas.','<div class="divorceNotice">Mapeamento de apoio: KRIM — geral; YOSHUA — traumas e sentimentos; KLIM — amor; SRIM — profissional/financeiro/material; SHIN — saúde física; HRIM — relações/família/amizade; 72 Nomes de Deus — questões espirituais/luto.</div>'+(remain.length?remain.map(specificBlock).join(''):'<div class="divorceNotice"><strong>Nenhuma área permaneceu ativa.</strong> Você pode seguir para a validação final.</div>'))}
function renderFinish(){const init=AREAS.filter(a=>s.initial[a.id]===true),remain=AREAS.filter(a=>s.rescan[a.id]===true);return shell('Validação final','Pendule se o trabalho está 100% finalizado nesta sessão. Se a resposta for Não, registre o que precisa de acompanhamento.','<div class="divorceSummary"><div class="divorceSummaryItem"><strong>'+init.length+' áreas identificadas inicialmente</strong><small>'+init.map(x=>esc(x.label)).join(' • ')+'</small></div><div class="divorceSummaryItem"><strong>'+remain.length+' áreas permaneceram após o tratamento geral</strong><small>'+(remain.length?remain.map(x=>esc(x.label)).join(' • '):'Nenhuma')+'</small></div></div><div class="divorceFinalChoice"><button type="button" data-final="yes" class="'+(s.finalized===true?'selected':'')+'">Sim, 100%</button><button type="button" data-final="no" class="'+(s.finalized===false?'selected':'')+'">Não</button></div>'+(s.finalized===false?'<div class="divorceField"><label>O que precisa continuar?</label><textarea id="divFollowup" placeholder="Próxima sessão, área, gráfico ou observação...">'+esc(s.followup)+'</textarea></div>':'')+'<div class="divorceField"><label>Observações finais <span class="optional">opcional</span></label><textarea id="divNotes">'+esc(s.notes)+'</textarea></div>', 'Concluir e gerar relatório')}
function parseBulk(text){return String(text||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean).map(line=>{const parts=line.split(/\s+[—–-]\s+|\t|;/);const name=(parts[0]||'').trim();let birth='';const raw=(parts[1]||'').trim();const m=raw.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);if(m)birth=`${m[3]}-${String(m[2]).padStart(2,'0')}-${String(m[1]).padStart(2,'0')}`;else if(/^\d{4}-\d{2}-\d{2}$/.test(raw))birth=raw;return{name,birthDate:birth}}).filter(x=>x.name)}
function collect(){if(!s)return;
 document.querySelectorAll('[data-person-name]').forEach(el=>{const i=+el.dataset.personName;if(s.people[i])s.people[i].name=el.value});document.querySelectorAll('[data-person-birth]').forEach(el=>{const i=+el.dataset.personBirth;if(s.people[i])s.people[i].birthDate=el.value});
 if($('divDate'))s.sessionDate=$('divDate').value;if($('divThemeOther'))s.themeOther=$('divThemeOther').value;if($('divIntention'))s.intention=$('divIntention').value;
 ['general','cut'].forEach(p=>{if($(p+'Graph'))s[p].graph=$(p+'Graph').value;if($(p+'Command'))s[p].command=$(p+'Command').value;if($(p+'Qty'))s[p].quantity=$(p+'Qty').value;if($(p+'Unit'))s[p].unit=$(p+'Unit').value;if($(p+'Done'))s[p].done=$(p+'Done').checked});
 document.querySelectorAll('[data-specific-graph]').forEach(el=>s.specific[el.dataset.specificGraph].graph=el.value);document.querySelectorAll('[data-specific-command]').forEach(el=>s.specific[el.dataset.specificCommand].command=el.value);document.querySelectorAll('[data-specific-qty]').forEach(el=>s.specific[el.dataset.specificQty].quantity=el.value);document.querySelectorAll('[data-specific-unit]').forEach(el=>s.specific[el.dataset.specificUnit].unit=el.value);document.querySelectorAll('[data-specific-done]').forEach(el=>s.specific[el.dataset.specificDone].done=el.checked);
 if($('divFollowup'))s.followup=$('divFollowup').value;if($('divNotes'))s.notes=$('divNotes').value;
}
function bind(){
 $('divBack')?.addEventListener('click',()=>{collect();persist();if(step===0)return home();step--;render()});$('divNext')?.addEventListener('click',()=>{collect();persist();if(step===7)return finish();step++;render()});
 document.querySelectorAll('[data-session-type]').forEach(b=>b.onclick=()=>{collect();s.sessionType=b.dataset.sessionType;if(s.sessionType==='individual'&&s.people.length>1)s.people=[s.people[0]];renderNoScroll()});
 $('addDivPerson')?.addEventListener('click',()=>{collect();s.people.push(blankPerson());renderNoScroll()});document.querySelectorAll('[data-remove-person]').forEach(b=>b.onclick=()=>{collect();s.people.splice(+b.dataset.removePerson,1);if(!s.people.length)s.people=[blankPerson()];renderNoScroll()});
 $('importDivBulk')?.addEventListener('click',()=>{const parsed=parseBulk($('divBulk')?.value);if(parsed.length){s.people=parsed;renderNoScroll()}});document.querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>{collect();s.theme=b.dataset.theme;renderNoScroll()});
 document.querySelectorAll('[data-anchor]').forEach(el=>el.onchange=()=>{s.anchoring[el.dataset.anchor]=el.checked;persist()});
 document.querySelectorAll('[data-area]').forEach(b=>b.onclick=()=>{const target=step===2?s.initial:s.rescan;target[b.dataset.area]=b.dataset.value==='yes';const pos=window.scrollY;const host=$('divorceView');const r=step===2?renderAreas:renderRescan;host.innerHTML=r();bind();requestAnimationFrame(()=>window.scrollTo(0,pos))});
 document.querySelectorAll('[data-final]').forEach(b=>b.onclick=()=>{collect();s.finalized=b.dataset.final==='yes';renderNoScroll()});
}
function renderNoScroll(){const pos=window.scrollY;const host=$('divorceView');const r=[renderSetup,renderAnchor,renderAreas,renderGeneral,renderCut,renderRescan,renderSpecific,renderFinish][step];host.innerHTML=r();bind();requestAnimationFrame(()=>window.scrollTo(0,pos))}
function finish(){collect();s.status='completed';s.completedAt=new Date().toISOString();persist();renderReport()}
function participants(){return s.people.filter(p=>p.name).map(p=>p.name+(p.birthDate?` (${new Date(p.birthDate+'T00:00:00').toLocaleDateString('pt-BR')})`:'')).join(' • ')||'Não informado'}
function renderReport(){show();const init=AREAS.filter(a=>s.initial[a.id]===true),remain=AREAS.filter(a=>s.rescan[a.id]===true);const specific=remain.map(a=>({a,o:s.specific[a.id]}));$('divorceView').innerHTML=`<div class="divorceShell divorceReport"><div class="divorceCard"><span class="pill">Sessão concluída</span><div class="divorceHeader"><h2>Divórcio Energético — relatório</h2><p>${esc(new Date(s.sessionDate+'T00:00:00').toLocaleDateString('pt-BR'))} • ${s.sessionType==='collective'?'Sessão coletiva':'Sessão individual'}</p></div><p><b>Participantes:</b> ${esc(participants())}</p>${s.theme?`<p><b>Tema:</b> ${esc(s.theme==='Outro'?(s.themeOther||'Outro'):s.theme)}</p>`:''}${s.intention?`<p><b>Intenção:</b> ${esc(s.intention)}</p>`:''}</div><div class="divorceCard"><h3>Leitura das áreas</h3><div class="divorceSummary"><div class="divorceSummaryItem"><strong>Antes do tratamento geral</strong><small>${init.length?init.map(x=>esc(x.label)).join(' • '):'Nenhuma área marcada'}</small></div><div class="divorceSummaryItem"><strong>Após o tratamento geral</strong><small>${remain.length?remain.map(x=>esc(x.label)).join(' • '):'Nenhuma área permaneceu ativa'}</small></div></div></div><div class="divorceCard"><h3>Tratamento geral</h3><p><b>Gráfico:</b> ${esc(s.general.graph)}</p><p>${esc(s.general.command)}</p><p><b>Tempo:</b> ${esc(duration(s.general))}</p><p><b>Realizado:</b> ${s.general.done?'Sim':'Não registrado'}</p><div class="reportTreatment"><h4>Corte geral</h4><p><b>Gráfico:</b> ${esc(s.cut.graph)}</p><p>${esc(s.cut.command)}</p><p><b>Tempo:</b> ${esc(duration(s.cut))}</p><p><b>Realizado:</b> ${s.cut.done?'Sim':'Não registrado'}</p></div></div><div class="divorceCard"><h3>Tratamentos específicos</h3>${specific.length?specific.map(({a,o})=>`<div class="reportTreatment"><h4>${esc(a.label)}</h4><p><b>Gráfico:</b> ${esc(o?.graph||a.graph)}</p><p>${esc(o?.command||COMMANDS[a.id])}</p><p><b>Tempo:</b> ${esc(duration(o))}</p><p><b>Realizado:</b> ${o?.done?'Sim':'Não registrado'}</p></div>`).join(''):'<p class="muted">Nenhum tratamento específico foi necessário.</p>'}</div><div class="divorceCard"><h3>Validação final</h3><p><b>100% finalizado nesta sessão:</b> ${s.finalized===true?'Sim':s.finalized===false?'Não':'Não registrado'}</p>${s.followup?`<p><b>Acompanhamento:</b> ${esc(s.followup)}</p>`:''}${s.notes?`<p><b>Observações:</b> ${esc(s.notes)}</p>`:''}</div><div class="divorceCard noPrint"><div class="divorceActions"><button id="divHome" class="ghost">Voltar ao início</button><button id="divPrint" class="primary">Salvar em PDF</button></div></div></div>`;$('divHome')?.addEventListener('click',home);$('divPrint')?.addEventListener('click',()=>window.print())}
function appendHistory(){const box=$('historyList');if(!box||box.dataset.divorceInjected==='1')return;const arr=load().filter(x=>x.status==='completed');if(!arr.length)return;box.dataset.divorceInjected='1';const label=document.createElement('p');label.className='historyLegacyLabel';label.textContent='Divórcio Energético';box.appendChild(label);arr.forEach(x=>{const d=document.createElement('details');d.className='historyCard';const init=AREAS.filter(a=>x.initial?.[a.id]===true),remain=AREAS.filter(a=>x.rescan?.[a.id]===true);d.innerHTML=`<summary><span><b>Divórcio Energético</b><small>${esc(new Date(x.sessionDate+'T00:00:00').toLocaleDateString('pt-BR'))} • ${x.sessionType==='collective'?'coletiva':'individual'} • ${init.length} áreas</small></span><span class="historyChevron">⌄</span></summary><div class="historyDetails divorceHistoryDetails"><span class="divorceHistoryBadge">${x.finalized===true?'100% finalizado':x.finalized===false?'Acompanhamento indicado':'Validação não registrada'}</span><p><b>Participantes:</b> ${esc((x.people||[]).filter(p=>p.name).map(p=>p.name).join(', ')||'Não informado')}</p>${x.theme?`<p><b>Tema:</b> ${esc(x.theme==='Outro'?(x.themeOther||'Outro'):x.theme)}</p>`:''}<p><b>Áreas iniciais:</b> ${esc(init.map(a=>a.label).join(' • ')||'Nenhuma')}</p><p><b>Após tratamento geral:</b> ${esc(remain.map(a=>a.label).join(' • ')||'Nenhuma')}</p>${remain.length?'<ul>'+remain.map(a=>{const o=x.specific?.[a.id];return `<li>${esc(a.label)} — ${esc(o?.graph||a.graph)} — ${esc(duration(o))}</li>`}).join('')+'</ul>':''}${x.followup?`<p><b>Acompanhamento:</b> ${esc(x.followup)}</p>`:''}</div>`;box.appendChild(d)})}
function install(){ensureUI()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();