(function(){
'use strict';
let records=[];
const $=id=>document.getElementById(id);
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function hideHome(){ $('homeView')?.classList.add('hidden') }
function goHome(){['startView','questionView','priorityView','treatmentView','reportView','historyView'].forEach(id=>$(id)?.classList.add('hidden'));$('homeView')?.classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}
function openProtocol(mode){hideHome();const tab=document.querySelector('.tab[data-mode="'+mode+'"]');if(tab)tab.click();const copy=$('startCopy');if(copy)copy.classList.add('hidden');$('startView')?.classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}
function findingsFromResult(){return Array.from(document.querySelectorAll('#priorityList .check')).map((el,i)=>{const b=el.querySelector('b');const small=el.querySelector('small');let cmd=small?small.textContent.trim():'';cmd=cmd.replace(/^Comando sugerido:\s*/i,'');return{id:'item_'+i,label:b?b.textContent.trim():'Item '+(i+1),command:cmd,graphs:[{name:'',time:''}],notes:''}})}
function addGraphRow(rec,box,index){const row=document.createElement('div');row.className='graphRow';row.innerHTML=`<div class="field"><label>Gráfico ${index+1}</label><input class="graphName" placeholder="Ex.: Desimpregnador" value="${esc(rec.graphs[index].name)}"></div><div class="field"><label>Tempo</label><input class="graphTime" placeholder="Ex.: 10 min" value="${esc(rec.graphs[index].time)}"></div>`;row.querySelector('.graphName').addEventListener('input',e=>rec.graphs[index].name=e.target.value);row.querySelector('.graphTime').addEventListener('input',e=>rec.graphs[index].time=e.target.value);box.appendChild(row)}
function renderTreatment(){const host=$('treatmentItems');if(!host)return;records=findingsFromResult();host.innerHTML='';if(!records.length){host.innerHTML='<section class="card"><p class="muted">Nenhum item específico foi identificado para tratamento.</p></section>';return}records.forEach((rec,i)=>{const card=document.createElement('section');card.className='card treatmentCard';card.innerHTML=`<span class="pill">${i+1} de ${records.length}</span><h3>${esc(rec.label)}</h3><p class="fieldTitle">Comando sugerido</p><p class="command">${esc(rec.command)}</p><div class="graphs"></div><button type="button" class="ghost addGraph">+ Adicionar outro gráfico</button><div class="field"><label>Observações deste item</label><textarea class="itemNotes" placeholder="Percepções ou validações..."></textarea></div>`;const box=card.querySelector('.graphs');addGraphRow(rec,box,0);card.querySelector('.addGraph').onclick=()=>{rec.graphs.push({name:'',time:''});addGraphRow(rec,box,rec.graphs.length-1)};card.querySelector('.itemNotes').addEventListener('input',e=>rec.notes=e.target.value);host.appendChild(card)})}
function syncLegacyMethods(){const m=$('methods');if(m)m.value=records.map(r=>r.label+': '+r.graphs.filter(g=>g.name||g.time).map(g=>(g.name||'Gráfico')+' — '+(g.time||'tempo não registrado')).join('; ')).join('\n')}
function appendDetails(){const body=$('reportBody');if(!body||!records.length)return;body.querySelector('.treatmentDetails')?.remove();const sec=document.createElement('section');sec.className='card reportSection treatmentDetails';sec.innerHTML='<h3>Tratamento realizado</h3>';records.forEach(r=>{const d=document.createElement('div');d.className='reportTreatment';const gs=r.graphs.filter(g=>g.name||g.time);d.innerHTML=`<h4>${esc(r.label)}</h4><p><b>Comando:</b> ${esc(r.command)}</p>`+(gs.length?'<ul>'+gs.map(g=>`<li><b>${esc(g.name||'Gráfico')}</b> — ${esc(g.time||'tempo não registrado')}</li>`).join('')+'</ul>':'<p class="muted">Nenhum gráfico registrado.</p>')+(r.notes?`<p><b>Observações:</b> ${esc(r.notes)}</p>`:'');sec.appendChild(d)});body.appendChild(sec)}
function activeMode(){return document.querySelector('.tab.active')?.dataset.mode||'finance'}
function saveRichSession(){try{const mode=activeMode();const item={id:Date.now(),date:new Date().toISOString(),mode,title:(typeof DATA!=='undefined'&&DATA[mode]?DATA[mode].title:mode),initial:+($('initialIntensity')?.value||0),final:+($('finalIntensity')?.value||0),generalNotes:$('notes')?.value||'',records:JSON.parse(JSON.stringify(records))};let h=JSON.parse(localStorage.getItem('rt_rich_sessions')||'[]');h.unshift(item);localStorage.setItem('rt_rich_sessions',JSON.stringify(h.slice(0,50)))}catch(e){}}
function legacySessions(){try{return JSON.parse(localStorage.getItem('rt_sessions_v2')||'[]')}catch(e){return[]}}
function richSessions(){try{return JSON.parse(localStorage.getItem('rt_rich_sessions')||'[]')}catch(e){return[]}}
function modeLabel(mode){return({finance:'Vida Financeira',career:'Carreira / Profissional',marriage:'Casamento / Relacionamento'})[mode]||mode||'Sessão'}
function renderDetailedHistory(){const box=$('historyList');if(!box)return;box.innerHTML='';const rich=richSessions();const legacy=legacySessions();if(!rich.length&&!legacy.length){box.innerHTML='<p class="muted">Nenhuma sessão salva ainda.</p>';return}
 rich.forEach(s=>{const dt=new Date(s.date);const d=document.createElement('details');d.className='historyCard';const recs=s.records||[];d.innerHTML=`<summary><span><b>${esc(s.title||modeLabel(s.mode))}</b><small>${esc(dt.toLocaleString('pt-BR'))} • ${s.initial}% → ${s.final}% • ${recs.length} itens</small></span><span class="historyChevron">⌄</span></summary><div class="historyDetails">`+(recs.length?recs.map(r=>{const gs=(r.graphs||[]).filter(g=>g.name||g.time);return `<div class="historyFinding"><b>${esc(r.label)}</b><p>${esc(r.command||'')}</p>`+(gs.length?'<ul>'+gs.map(g=>`<li>${esc(g.name||'Gráfico')} — ${esc(g.time||'tempo não registrado')}</li>`).join('')+'</ul>':'<p class="muted">Sem gráfico registrado.</p>')+(r.notes?`<p><b>Observações:</b> ${esc(r.notes)}</p>`:'')+'</div>'}).join(''):'<p class="muted">Nenhum item detalhado registrado.</p>')+(s.generalNotes?`<div class="historyGeneral"><b>Observações gerais</b><p>${esc(s.generalNotes)}</p></div>`:'')+'</div>';box.appendChild(d)});
 if(legacy.length){const label=document.createElement('p');label.className='historyLegacyLabel';label.textContent=rich.length?'Sessões anteriores':'';box.appendChild(label);legacy.forEach(s=>{const d=document.createElement('details');d.className='historyCard legacy';const dt=new Date(s.date);const tags=(s.findings||[]).map(t=>(typeof PLANS!=='undefined'&&PLANS[t]?PLANS[t].label:t));d.innerHTML=`<summary><span><b>${esc(s.title||modeLabel(s.mode))}</b><small>${esc(dt.toLocaleString('pt-BR'))} • ${s.initial}% → ${s.final}%</small></span><span class="historyChevron">⌄</span></summary><div class="historyDetails">`+(tags.length?`<div class="historyFinding"><b>Achados registrados</b><ul>${tags.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:'')+(s.methods?`<div class="historyFinding"><b>Gráficos / métodos registrados</b><p>${esc(s.methods)}</p></div>`:'')+(s.notes?`<div class="historyFinding"><b>Observações</b><p>${esc(s.notes)}</p></div>`:'')+'<p class="muted historyNote">Sessão criada em uma versão anterior; alguns detalhes individuais podem não ter sido armazenados.</p></div>';box.appendChild(d)})}}
function install(){
 $('startView')?.classList.add('hidden');$('homeView')?.classList.remove('hidden');
 document.querySelectorAll('[data-open-mode]').forEach(b=>b.onclick=()=>openProtocol(b.dataset.openMode));
 document.querySelectorAll('.backHome').forEach(b=>b.onclick=goHome);$('headerHomeBtn')?.addEventListener('click',goHome);
 $('toTreatmentBtn')?.addEventListener('click',()=>setTimeout(()=>{renderTreatment();window.scrollTo({top:0,behavior:'smooth'})},0));
 $('makeReportBtn')?.addEventListener('click',()=>{syncLegacyMethods();saveRichSession();setTimeout(()=>{appendDetails();window.scrollTo({top:0,behavior:'smooth'})},20)});
 $('printBtn')?.addEventListener('click',()=>window.print());$('historyBtn')?.addEventListener('click',()=>{hideHome();setTimeout(renderDetailedHistory,20)});$('closeHistory')?.addEventListener('click',goHome);$('newBtn')?.addEventListener('click',goHome);
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();