(function(){
'use strict';
const $=id=>document.getElementById(id);
const LANG_KEY='lumera_language_v13';
const ASSESSMENT_STORE='rt_assessments_v1';
const DIVORCE_STORE='rt_divorce_sessions_v1';
const SESSION_STORE='rt_sessions_v4';
const V14_PREF='lumera_v14_session_mode';
const t=(pt,en)=>(localStorage.getItem(LANG_KEY)==='en'?en:pt);
const parse=k=>{try{return JSON.parse(localStorage.getItem(k)||'[]')}catch(e){return[]}};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const GROUPS={
 resources:{pt:'Dinheiro & carreira',en:'Money & career',modes:['finance','prosperity','career','creativity']},
 relations:{pt:'Relacionamentos',en:'Relationships',modes:['marriage','family','social','parenting']},
 self:{pt:'Eu & bem-estar',en:'Self & wellbeing',modes:['selfworth','bodyrelation','purpose','repeating','homeenv']},
 quick:{pt:'Sessões rápidas',en:'Quick sessions',modes:['quick_balance','quick_hardday','quick_decision','quick_cycle','quick_conflict']},
 master:{pt:'Mestre',en:'Master',modes:['master']}
};
function allModes(){return Object.values(GROUPS).flatMap(g=>g.modes)}
function latestDraft(){
 const assessments=parse(ASSESSMENT_STORE).filter(x=>x&&x.status==='draft').sort((a,b)=>new Date(b.createdAt||0)-new Date(a.createdAt||0));
 const divorces=parse(DIVORCE_STORE).filter(x=>x&&x.status==='draft').sort((a,b)=>new Date(b.createdAt||0)-new Date(a.createdAt||0));
 const a=assessments[0],d=divorces[0];
 if(a&&(!d||new Date(a.createdAt||0)>=new Date(d.createdAt||0)))return{type:'assessment',item:a};
 if(d)return{type:'divorce',item:d};
 return null;
}
function draftLabel(d){if(!d)return'';if(d.type==='assessment'){const id=d.item.identity||{};if(id.sessionType==='collective')return t('Avaliação coletiva em andamento','Group assessment in progress');return id.name||t('Avaliação inicial em andamento','Initial assessment in progress')}const p=(d.item.people||[]).find(x=>x.name);return p?.name||t('Divórcio Energético em andamento','Energetic Divorce in progress')}
function categoryFor(mode){for(const [k,g] of Object.entries(GROUPS))if(g.modes.includes(mode))return k;return'master'}
function modeTitle(mode){return window.DATA?.[mode]?.title||document.querySelector(`[data-open-mode="${mode}"] strong`)?.textContent||mode}
function modeCopy(mode){return document.querySelector(`[data-open-mode="${mode}"] small`)?.textContent||''}
function ensureLibrary(){if($('v14Library'))return;const v=document.createElement('section');v.id='v14Library';v.className='v14Overlay hidden';v.setAttribute('role','dialog');v.setAttribute('aria-modal','true');document.body.appendChild(v)}
function libraryHTML(initial='all'){
 const filters=[['all',t('Todos','All')],...Object.entries(GROUPS).map(([k,g])=>[k,t(g.pt,g.en)])];
 return `<div class="v14Sheet"><div class="v14SheetHead"><div><span class="micro">Lumera</span><h2>${t('Biblioteca de Protocolos','Protocol Library')}</h2><p>${t('Escolha apenas o que precisa agora. Você pode buscar por tema ou filtrar por categoria.','Choose only what you need now. Search by topic or filter by category.')}</p></div><button id="v14CloseLibrary" class="v14IconBtn" type="button" aria-label="${t('Fechar biblioteca','Close library')}">×</button></div><div class="v14Search"><input id="v14ProtocolSearch" type="search" placeholder="${t('Buscar protocolo…','Search protocols…')}" autocomplete="off"></div><div class="v14Filters" role="tablist">${filters.map(([k,l])=>`<button type="button" data-v14-filter="${k}" class="${k===initial?'active':''}">${esc(l)}</button>`).join('')}</div><div id="v14ProtocolList" class="v14ProtocolList"></div><div class="v14MasterHint"><div><strong>${t('Não sabe qual escolher?','Not sure which one to choose?')}</strong><small>${t('O Protocolo Mestre investiga diferentes tipos de causa sem exigir uma área prévia.','The Master Protocol explores different types of causes without requiring a predefined area.')}</small></div><button type="button" data-v14-mode="master" class="ghost">${t('Abrir Mestre','Open Master')}</button></div></div>`
}
function renderProtocolList(filter='all',query=''){
 const host=$('v14ProtocolList');if(!host)return;const q=query.trim().toLocaleLowerCase();const modes=allModes().filter(m=>(filter==='all'||categoryFor(m)===filter)).filter(m=>{if(!q)return true;return `${modeTitle(m)} ${modeCopy(m)}`.toLocaleLowerCase().includes(q)});
 host.innerHTML=modes.length?modes.map(m=>`<button class="v14ProtocolItem" type="button" data-v14-mode="${m}"><span class="v14ProtocolDot">${categoryFor(m)==='quick'?'◌':categoryFor(m)==='master'?'◎':'✦'}</span><span><strong>${esc(modeTitle(m))}</strong><small>${esc(modeCopy(m))}</small></span><span class="chevron">›</span></button>`).join(''):`<div class="v14Empty">${t('Nenhum protocolo encontrado.','No protocols found.')}</div>`;
 host.querySelectorAll('[data-v14-mode]').forEach(b=>b.onclick=()=>openMode(b.dataset.v14Mode));
}
function openLibrary(initial='all'){ensureLibrary();const v=$('v14Library');v.innerHTML=libraryHTML(initial);v.classList.remove('hidden');document.body.classList.add('v14ModalOpen');renderProtocolList(initial,'');$('v14CloseLibrary').onclick=closeLibrary;$('v14ProtocolSearch').oninput=e=>renderProtocolList(document.querySelector('[data-v14-filter].active')?.dataset.v14Filter||'all',e.target.value);v.querySelectorAll('[data-v14-filter]').forEach(b=>b.onclick=()=>{v.querySelectorAll('[data-v14-filter]').forEach(x=>x.classList.toggle('active',x===b));renderProtocolList(b.dataset.v14Filter,$('v14ProtocolSearch').value)});v.querySelectorAll('.v14MasterHint [data-v14-mode]').forEach(b=>b.onclick=()=>openMode(b.dataset.v14Mode));$('v14ProtocolSearch')?.focus()}
function closeLibrary(){$('v14Library')?.classList.add('hidden');document.body.classList.remove('v14ModalOpen')}
function openMode(mode){closeLibrary();const src=document.querySelector(`[data-open-mode="${mode}"]`);if(src){src.click();setTimeout(updateSessionMode,30);return}const tab=document.querySelector(`.tab[data-mode="${mode}"]`);if(tab){tab.click();document.querySelector('[data-open-mode]')?.click()}}
function startAssessment(){$('startAssessmentBtn')?.click()}
function startDivorce(){$('openDivorceBtn')?.click()}
function resumeDraft(){const d=latestDraft();if(!d)return;if(d.type==='assessment'){const history=$('historyBtn');history?.click();setTimeout(()=>{const resume=document.querySelector(`[data-resume="${d.item.id}"]`);if(resume)resume.click();else{document.getElementById('closeHistory')?.click();startAssessment()}},120)}else{const history=$('historyBtn');history?.click();}}
function dashboardHTML(){const d=latestDraft();return `<section class="v14Dashboard" aria-labelledby="v14HomeTitle"><div class="v14DashboardHead"><span class="eyebrow">Lumera</span><h1 id="v14HomeTitle">${t('O que você quer fazer agora?','What would you like to do now?')}</h1><p>${t('Acesse apenas o fluxo que precisa. Sua jornada de preparação do dia continua separada das análises individuais.','Open only the workflow you need. Your daily preparation remains separate from individual analyses.')}</p></div>${d?`<button id="v14Resume" class="v14Resume" type="button"><span class="v14ResumeIcon">↻</span><span><small>${t('Continuar de onde parei','Continue where I left off')}</small><strong>${esc(draftLabel(d))}</strong><em>${d.type==='assessment'?t('Retomar avaliação','Resume assessment'):t('Abrir histórico para retomar','Open history to resume')}</em></span><span class="chevron">›</span></button>`:''}<div class="v14Actions"><button id="v14Assessment" class="v14Action primaryAction" type="button"><span>＋</span><strong>${t('Nova avaliação','New assessment')}</strong><small>${t('Avaliação inicial completa','Complete initial assessment')}</small></button><button id="v14LibraryBtn" class="v14Action" type="button"><span>◎</span><strong>${t('Iniciar investigação','Start investigation')}</strong><small>${t('Abrir biblioteca de protocolos','Open protocol library')}</small></button><button id="v14Divorce" class="v14Action" type="button"><span>↯</span><strong>${t('Divórcio Energético','Energetic Divorce')}</strong><small>${t('Fluxo individual ou coletivo','Individual or group flow')}</small></button><button id="v14Quick" class="v14Action" type="button"><span>◌</span><strong>${t('Sessão rápida','Quick session')}</strong><small>${t('Reequilíbrio sem investigação extensa','Rebalancing without deep investigation')}</small></button></div><div class="v14Secondary"><button id="v14History" class="ghost" type="button">${t('Clientes e histórico','Clients & history')}</button><button id="v14PrepJump" class="ghost" type="button">${t('Jornada do terapeuta','Practitioner journey')}</button></div></section>`}
function installDashboard(){const home=$('homeView');if(!home)return;home.classList.add('v14DashboardHome');let d=$('v14Dashboard');if(!d){const wrap=document.createElement('div');wrap.id='v14Dashboard';home.prepend(wrap);d=wrap}d.innerHTML=dashboardHTML();$('v14Resume')?.addEventListener('click',resumeDraft);$('v14Assessment')?.addEventListener('click',startAssessment);$('v14LibraryBtn')?.addEventListener('click',()=>openLibrary('all'));$('v14Divorce')?.addEventListener('click',startDivorce);$('v14Quick')?.addEventListener('click',()=>openLibrary('quick'));$('v14History')?.addEventListener('click',()=>$('historyBtn')?.click());$('v14PrepJump')?.addEventListener('click',()=>document.querySelector('.lumeraWorkspace')?.scrollIntoView({behavior:'smooth',block:'start'}))}
function ensureFocusToggle(){if($('v14FocusToggle'))return;const b=document.createElement('button');b.id='v14FocusToggle';b.type='button';b.className='v14FocusToggle hidden';b.innerHTML='◉ <span>'+t('Modo Sessão','Session Mode')+'</span>';b.onclick=()=>{const on=!document.body.classList.contains('v14FocusMode');document.body.classList.toggle('v14FocusMode',on);sessionStorage.setItem(V14_PREF,on?'1':'0');b.classList.toggle('active',on);b.querySelector('span').textContent=on?t('Sair do modo sessão','Exit session mode'):t('Modo Sessão','Session Mode')};document.body.appendChild(b)}
function activeWorkView(){return['startView','questionView','priorityView','causalView','treatmentView','assessmentView','reevalView','divorceView'].some(id=>{const e=$(id);return e&&!e.classList.contains('hidden')})}
function updateSessionMode(){ensureFocusToggle();const active=activeWorkView();const b=$('v14FocusToggle');b?.classList.toggle('hidden',!active);if(!active){document.body.classList.remove('v14FocusMode');sessionStorage.removeItem(V14_PREF);b?.classList.remove('active');return}if(sessionStorage.getItem(V14_PREF)==='1'){document.body.classList.add('v14FocusMode');b?.classList.add('active');if(b?.querySelector('span'))b.querySelector('span').textContent=t('Sair do modo sessão','Exit session mode')}}
function install(){ensureLibrary();installDashboard();ensureFocusToggle();updateSessionMode();const obs=new MutationObserver(()=>{clearTimeout(obs._t);obs._t=setTimeout(()=>{if($('homeView')&&!$('homeView').classList.contains('hidden'))installDashboard();updateSessionMode()},50)});obs.observe(document.body,{subtree:true,attributes:true,attributeFilter:['class']});window.addEventListener('storage',()=>{if($('homeView')&&!$('homeView').classList.contains('hidden'))installDashboard()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('v14Library')?.classList.contains('hidden'))closeLibrary()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();