(function(){
'use strict';
const $=id=>document.getElementById(id);
const LANG='lumera_language_v13';
const STORES={sessions:'rt_sessions_v4',assessments:'rt_assessments_v1',divorces:'rt_divorce_sessions_v1'};
const t=(pt,en)=>localStorage.getItem(LANG)==='en'?en:pt;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const load=k=>{try{return JSON.parse(localStorage.getItem(k)||'[]')}catch(e){return[]}};
const fmt=d=>{if(!d)return'';try{return new Date(d).toLocaleString(localStorage.getItem(LANG)==='en'?'en-CA':'pt-BR',{dateStyle:'medium',timeStyle:'short'})}catch(e){return String(d)}};
const norm=s=>String(s||'').trim().toLocaleLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const dur=g=>{const q=Number(g?.quantity||0),u=g?.unit||'';if(!q)return'';const map={minutos:['minuto','minutos'],horas:['hora','horas'],dias:['dia','dias'],semanas:['semana','semanas'],meses:['mês','meses']};const en={minutos:['minute','minutes'],horas:['hour','hours'],dias:['day','days'],semanas:['week','weeks'],meses:['month','months']};const m=localStorage.getItem(LANG)==='en'?en:map,v=m[u]||[u,u];return `${q} ${q===1?v[0]:v[1]}`};
function assessmentIdentity(a){const id=a?.identity||{};if(id.sessionType==='collective'){const p=(id.participants||[]).filter(x=>x.name);return{type:'group',name:p.length?p.map(x=>x.name).join(', '):t('Sessão coletiva','Group session'),people:p,birth:''}}return{type:'individual',name:id.name||t('Sem nome','Unnamed'),people:id.name?[{name:id.name,birthDate:id.birthDate||''}]:[],birth:id.birthDate||''}}
function divorceIdentity(d){const p=(d?.people||[]).filter(x=>x.name);if(d?.sessionType==='collective'||p.length>1)return{type:'group',name:p.length?p.map(x=>x.name).join(', '):t('Sessão coletiva','Group session'),people:p,birth:''};return{type:'individual',name:p[0]?.name||t('Sem nome','Unnamed'),people:p,birth:p[0]?.birthDate||''}}
function clientKey(id){if(id.type==='group')return'group:'+id.people.map(p=>norm(p.name)+'|'+(p.birthDate||'')).sort().join('~');return'individual:'+norm(id.name)+'|'+(id.birth||'')}
function buildRecords(){const sessions=load(STORES.sessions),assessments=load(STORES.assessments),divorces=load(STORES.divorces),used=new Set(),out=[];
 sessions.forEach(s=>{const a=assessments.find(x=>String(x.linkedSessionId)===String(s.id));if(a)used.add(String(a.id));const id=a?assessmentIdentity(a):{type:'unknown',name:t('Sem cliente vinculado','Unlinked client'),people:[],birth:''};out.push({id:'s:'+s.id,kind:'protocol',date:s.date||a?.createdAt,status:'completed',title:s.title||s.mode||t('Protocolo','Protocol'),identity:id,clientKey:a?clientKey(id):'unknown',session:s,assessment:a})});
 assessments.filter(a=>!used.has(String(a.id))).forEach(a=>{const id=assessmentIdentity(a),draft=a.status==='draft'||a.status==='protocol-pending';out.push({id:'a:'+a.id,kind:'assessment',date:a.createdAt||a.identity?.sessionDate,status:draft?'draft':'completed',title:t('Avaliação inicial','Initial assessment'),identity:id,clientKey:clientKey(id),assessment:a})});
 divorces.forEach(d=>{const id=divorceIdentity(d),draft=d.status==='draft';out.push({id:'d:'+d.id,kind:'divorce',date:d.createdAt||d.sessionDate,status:draft?'draft':'completed',title:t('Divórcio Energético','Energetic Divorce'),identity:id,clientKey:clientKey(id),divorce:d})});
 return out.sort((a,b)=>new Date(b.date||0)-new Date(a.date||0))}
function kindLabel(r){return r.kind==='assessment'?t('Avaliação','Assessment'):r.kind==='divorce'?t('Divórcio Energético','Energetic Divorce'):t('Protocolo','Protocol')}
function statusLabel(r){return r.status==='draft'?t('Rascunho','Draft'):t('Concluído','Completed')}
function summaryFor(r){if(r.kind==='protocol'){const s=r.session,n=(s.treatment||[]).length;return `${s.initial??'—'}% → ${s.final??'—'}% • ${n} ${t('item(ns) tratado(s)','treated item(s)')}`}
 if(r.kind==='assessment'){const a=r.assessment,life=Object.values(a.lifeAreas||{}).filter(v=>v!==''&&v!=null).map(Number);return life.length?t('Maior desequilíbrio: ','Highest imbalance: ')+Math.max(...life)+'%':t('Avaliação registrada','Assessment recorded')}
 const d=r.divorce,active=Object.values(d.initial||{}).filter(v=>v===true).length;return `${active} ${t('área(s) identificada(s)','identified area(s)')} • ${d.finalized===true?'100% '+t('finalizado','completed'):statusLabel(r)}`}
function recordCard(r){const group=r.identity.type==='group';return `<article class="v15Record"><div class="v15RecordTop"><span class="v15Kind">${esc(kindLabel(r))}</span><span class="v15Status ${r.status==='draft'?'draft':''}">${esc(statusLabel(r))}</span></div><h3>${esc(r.identity.name)}</h3><strong class="v15RecordTitle">${esc(r.title)}</strong><p>${esc(summaryFor(r))}</p><small>${esc(fmt(r.date))}${group?' • '+t('coletivo','group'):''}</small>${recordDetails(r)}</article>`}
function recordDetails(r){if(r.kind==='protocol'){const s=r.session,items=(s.treatment||[]);return `<details><summary>${t('Ver detalhes','View details')}</summary><div class="v15Details">${items.map(x=>`<p><b>${esc(x.label)}</b>${x.classification?' • '+esc(x.classification):''}</p>`).join('')||`<p>${t('Sem itens tratados registrados.','No treated items recorded.')}</p>`}</div></details>`}
 if(r.kind==='assessment'){const a=r.assessment,rows=Object.values(a.reevaluation||{}).filter(x=>x&&x.after!=='');return `<details><summary>${t('Ver detalhes','View details')}</summary><div class="v15Details">${a.identity?.relato?`<p><b>${t('Relato','Notes')}:</b> ${esc(a.identity.relato)}</p>`:''}${rows.length?rows.map(x=>`<p>${esc(x.label)}: <b>${esc(x.before)}${x.type==='percent'?'%':''} → ${esc(x.after)}${x.type==='percent'?'%':''}</b></p>`).join(''):''}</div></details>`}
 const d=r.divorce;return `<details><summary>${t('Ver detalhes','View details')}</summary><div class="v15Details">${d.theme?`<p><b>${t('Tema','Theme')}:</b> ${esc(d.theme)}</p>`:''}${d.followup?`<p><b>${t('Acompanhamento','Follow-up')}:</b> ${esc(d.followup)}</p>`:''}</div></details>`}
function groupClients(records){const map=new Map();records.filter(r=>r.clientKey!=='unknown').forEach(r=>{if(!map.has(r.clientKey))map.set(r.clientKey,{identity:r.identity,records:[]});map.get(r.clientKey).records.push(r)});return [...map.values()].sort((a,b)=>new Date(b.records[0]?.date||0)-new Date(a.records[0]?.date||0))}
function clientCard(c){const last=c.records[0],group=c.identity.type==='group';return `<article class="v15Client"><div class="v15ClientHead"><div class="v15Avatar">${group?'∞':esc((c.identity.name||'?').charAt(0).toUpperCase())}</div><div><h3>${esc(c.identity.name)}</h3><p>${c.records.length} ${t('registro(s)','record(s)')} • ${t('último','latest')}: ${esc(fmt(last.date))}</p></div></div><details><summary>${t('Ver histórico','View history')}</summary><div class="v15ClientTimeline">${c.records.map(recordCard).join('')}</div></details></article>`}
function controlsHTML(){return `<div class="v15HistoryTools"><div class="v15ViewTabs"><button data-v15-view="timeline" class="active">${t('Linha do tempo','Timeline')}</button><button data-v15-view="clients">${t('Clientes / grupos','Clients / groups')}</button></div><input id="v15HistorySearch" type="search" placeholder="${t('Buscar nome, protocolo ou tema…','Search name, protocol or topic…')}"><div class="v15RecordFilters"><button data-v15-filter="all" class="active">${t('Todos','All')}</button><button data-v15-filter="individual">${t('Individuais','Individual')}</button><button data-v15-filter="group">${t('Coletivos','Groups')}</button><button data-v15-filter="draft">${t('Rascunhos','Drafts')}</button></div></div><div id="v15RecordsHost"></div>`}
let view='timeline',filter='all',query='';
function matches(r){if(filter==='individual'&&r.identity.type!=='individual')return false;if(filter==='group'&&r.identity.type!=='group')return false;if(filter==='draft'&&r.status!=='draft')return false;if(!query)return true;const hay=[r.identity.name,r.title,r.divorce?.theme,r.assessment?.identity?.relato,(r.session?.treatment||[]).map(x=>x.label).join(' ')].join(' ').toLocaleLowerCase();return hay.includes(query.toLocaleLowerCase())}
function paint(){const host=$('v15RecordsHost');if(!host)return;const records=buildRecords().filter(matches);if(!records.length){host.innerHTML=`<div class="v15Empty">${t('Nenhum registro encontrado.','No records found.')}</div>`;return}host.innerHTML=view==='timeline'?`<div class="v15Timeline">${records.map(recordCard).join('')}</div>`:`<div class="v15Clients">${groupClients(records).map(clientCard).join('')}</div>`}
function renderHistory(){const box=$('historyList'),hv=$('historyView');if(!box||!hv)return;hv.querySelector('.historyHead h2').textContent=t('Clientes e Histórico','Clients & History');const p=hv.querySelector(':scope > p.muted');if(p)p.textContent=t('Encontre trabalhos por pessoa, grupo, data ou protocolo. A linha do tempo cronológica continua disponível.','Find work by person, group, date or protocol. The chronological timeline remains available.');box.innerHTML=controlsHTML();box.dataset.v15='1';box.querySelectorAll('[data-v15-view]').forEach(b=>b.onclick=()=>{view=b.dataset.v15View;box.querySelectorAll('[data-v15-view]').forEach(x=>x.classList.toggle('active',x===b));paint()});box.querySelectorAll('[data-v15-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.v15Filter;box.querySelectorAll('[data-v15-filter]').forEach(x=>x.classList.toggle('active',x===b));paint()});$('v15HistorySearch').oninput=e=>{query=e.target.value.trim();paint()};paint()}
function linkedAssessment(s){return load(STORES.assessments).find(a=>String(a.linkedSessionId)===String(s?.id))}
function classification(it){if(!it)return'';if(it.quick)return t('Foco da sessão rápida','Quick-session focus');if(it.root===true)return it.priority?t('Causa raiz • prioridade','Root cause • priority'):t('Causa raiz','Root cause');if(it.priorCause===true)return t('Consequência de causa anterior','Consequence of a prior cause')+(it.origin?' • '+it.origin:'');return t('Fator associado / intermediário','Associated / intermediate factor')}
function reportSummary(s,a){const ident=a?assessmentIdentity(a):{name:t('Sem cliente vinculado','Unlinked client'),type:'unknown'};const caus=(s.causal?.items||[]),treated=s.treatment||[],follow=caus.filter(x=>x.followup===true),roots=caus.filter(x=>x.root===true),graphs=treated.flatMap(x=>(x.graphs||[]).filter(g=>g.name||g.quantity).map(g=>({item:x.label,name:g.name||t('Gráfico','Chart'),time:dur(g)})));const cmp=a?Object.values(a.reevaluation||{}).filter(x=>x&&x.after!==''):[];return `<section class="card v15ReportSummary"><div class="v15ReportHero"><span>${t('Resumo da sessão','Session summary')}</span><h2>${esc(ident.name)}</h2><p>${esc(s.title)} • ${esc(fmt(s.date))}${ident.type==='group'?' • '+t('coletivo','group'):''}</p></div><div class="v15MetricGrid"><div><small>${t('Desequilíbrio geral','Overall imbalance')}</small><strong>${esc(s.initial)}% → ${esc(s.final)}%</strong></div><div><small>${t('Itens tratados','Treated items')}</small><strong>${treated.length}</strong></div><div><small>${t('Acompanhamento','Follow-up')}</small><strong>${follow.length?t('Indicado','Recommended'):t('Não indicado','Not indicated')}</strong></div></div>${cmp.length?`<div class="v15ReportBlock"><h3>${t('Antes × Depois','Before × After')}</h3><div class="v15Comparison">${cmp.map(r=>`<div><span>${esc(r.label)}</span><b>${esc(r.before)}${r.type==='percent'?'%':esc(r.unit||'')} → ${esc(r.after)}${r.type==='percent'?'%':esc(r.unit||'')}</b></div>`).join('')}</div></div>`:''}<div class="v15ReportGrid"><div class="v15ReportBlock"><h3>${t('Principais achados e causas','Key findings & causes')}</h3>${caus.length?`<ul>${caus.map(x=>`<li><b>${esc(x.label)}</b><small>${esc(classification(x))}</small></li>`).join('')}</ul>`:`<p>${t('Nenhuma causa classificada registrada.','No classified cause recorded.')}</p>`}</div><div class="v15ReportBlock"><h3>${t('Tratamentos e gráficos','Treatments & charts')}</h3>${graphs.length?`<ul>${graphs.map(g=>`<li><b>${esc(g.name)}</b><small>${esc(g.item)}${g.time?' • '+esc(g.time):''}</small></li>`).join('')}</ul>`:`<p>${t('Nenhum gráfico registrado.','No chart recorded.')}</p>`}</div></div><div class="v15Followup ${follow.length?'needed':''}"><b>${t('Acompanhamento recomendado','Recommended follow-up')}</b><p>${follow.length?follow.map(x=>esc(x.label)).join(' • '):t('Nenhum item foi marcado como necessitando nova sessão específica.','No item was marked as requiring a specific follow-up session.')}</p></div></section>`}
function decorateReport(){const rv=$('reportView'),body=$('reportBody');if(!rv||rv.classList.contains('hidden')||!body)return;const s=load(STORES.sessions)[0];if(!s)return;body.querySelector('.v15ReportSummary')?.remove();body.insertAdjacentHTML('afterbegin',reportSummary(s,linkedAssessment(s)))}
function install(){const hv=$('historyView'),rv=$('reportView');let timer;const obs=new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(()=>{if(hv&&!hv.classList.contains('hidden'))renderHistory();if(rv&&!rv.classList.contains('hidden'))decorateReport()},180)});[hv,rv].forEach(x=>x&&obs.observe(x,{attributes:true,attributeFilter:['class']}));window.addEventListener('storage',()=>{if(hv&&!hv.classList.contains('hidden'))renderHistory()});if(hv&&!hv.classList.contains('hidden'))renderHistory();if(rv&&!rv.classList.contains('hidden'))decorateReport()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();