(function(){
'use strict';
const $=id=>document.getElementById(id);
const LANG='lumera_language_v13';
const t=(pt,en)=>localStorage.getItem(LANG)==='en'?en:pt;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const GROUPS={resources:['finance','prosperity','career','creativity'],relations:['marriage','family','social','parenting'],self:['selfworth','bodyrelation','purpose','repeating','homeenv'],quick:['quick_balance','quick_hardday','quick_decision','quick_cycle','quick_conflict'],master:['master']};
let filter='all',query='';
function allModes(){return [...new Set(Object.values(GROUPS).flat())]}
function group(mode){for(const [k,v] of Object.entries(GROUPS))if(v.includes(mode))return k;return'master'}
function title(mode){return window.DATA?.[mode]?.title||document.querySelector(`[data-open-mode="${mode}"] strong`)?.textContent||mode}
function copy(mode){return document.querySelector(`[data-open-mode="${mode}"] small`)?.textContent||''}
function dashboardHTML(){return `<section class="v16Dashboard" aria-labelledby="v16Title"><div class="v16Head"><h1 id="v16Title">${esc(t('O que você quer fazer agora?','What would you like to do now?'))}</h1><p>${esc(t('Escolha um fluxo para começar.','Choose a flow to begin.'))}</p></div><div class="v16Actions"><button type="button" data-v16-action="assessment" class="v16Action v16Primary"><span>＋</span><strong>${esc(t('Nova avaliação','New assessment'))}</strong><small>${esc(t('Avaliação inicial completa','Complete initial assessment'))}</small></button><button type="button" data-v16-action="library" class="v16Action"><span>◎</span><strong>${esc(t('Iniciar investigação','Start investigation'))}</strong><small>${esc(t('Abrir biblioteca de protocolos','Open protocol library'))}</small></button><button type="button" data-v16-action="divorce" class="v16Action"><span>↯</span><strong>${esc(t('Divórcio Energético','Energetic Divorce'))}</strong><small>${esc(t('Fluxo individual ou coletivo','Individual or group flow'))}</small></button><button type="button" data-v16-action="quick" class="v16Action"><span>◌</span><strong>${esc(t('Sessão rápida','Quick session'))}</strong><small>${esc(t('Reequilíbrio sem investigação extensa','Rebalancing without extensive investigation'))}</small></button></div><div class="v16Secondary"><button type="button" class="ghost" data-v16-action="history">${esc(t('Clientes e histórico','Clients & history'))}</button></div></section>`}
function renderDashboard(){const home=$('homeView');if(!home)return;let host=$('v16Dashboard');if(!host){host=document.createElement('div');host.id='v16Dashboard';home.prepend(host)}host.innerHTML=dashboardHTML()}
function ensureLibrary(){let o=$('v16Library');if(!o){o=document.createElement('div');o.id='v16Library';o.className='v16Overlay hidden';o.setAttribute('role','dialog');o.setAttribute('aria-modal','true');document.body.appendChild(o)}return o}
function paintList(){const host=$('v16List');if(!host)return;const q=query.trim().toLowerCase();const modes=allModes().filter(m=>filter==='all'||group(m)===filter).filter(m=>!q||`${title(m)} ${copy(m)}`.toLowerCase().includes(q));host.innerHTML=modes.length?modes.map(m=>`<button type="button" class="v16Protocol" data-v16-mode="${esc(m)}"><span>${group(m)==='quick'?'◌':group(m)==='master'?'◎':'✦'}</span><span><strong>${esc(title(m))}</strong><small>${esc(copy(m))}</small></span><b>›</b></button>`).join(''):`<div class="v16Empty">${esc(t('Nenhum protocolo encontrado.','No protocols found.'))}</div>`}
function openLibrary(which='all'){filter=which;query='';const o=ensureLibrary();o.innerHTML=`<div class="v16Sheet"><div class="v16SheetHead"><div><span>Lumera</span><h2>${esc(t('Biblioteca de protocolos','Protocol library'))}</h2></div><button type="button" data-v16-action="close-library" class="v16Close">×</button></div><label class="v16Search"><input id="v16Search" type="search" placeholder="${esc(t('Buscar protocolo…','Search protocols…'))}"></label><div class="v16Filters">${[['all',t('Todos','All')],['resources',t('Dinheiro & carreira','Money & career')],['relations',t('Relacionamentos','Relationships')],['self',t('Eu & bem-estar','Self & wellbeing')],['quick',t('Sessões rápidas','Quick sessions')],['master',t('Mestre','Master')]].map(([k,l])=>`<button type="button" data-v16-filter="${k}" class="${filter===k?'active':''}">${esc(l)}</button>`).join('')}</div><div id="v16List" class="v16List"></div></div>`;o.classList.remove('hidden');document.body.classList.add('v16ModalOpen');paintList()}
function closeLibrary(){const o=$('v16Library');if(o)o.classList.add('hidden');document.body.classList.remove('v16ModalOpen')}
function openMode(mode){closeLibrary();document.querySelector(`[data-open-mode="${CSS.escape(mode)}"]`)?.click()}
function act(a){if(a==='assessment')return $('startAssessmentBtn')?.click();if(a==='library')return openLibrary('all');if(a==='quick')return openLibrary('quick');if(a==='divorce')return $('openDivorceBtn')?.click();if(a==='history')return $('historyBtn')?.click();if(a==='close-library')return closeLibrary()}
function install(){renderDashboard();ensureLibrary();document.addEventListener('click',e=>{const a=e.target.closest('[data-v16-action]');if(a){e.preventDefault();act(a.dataset.v16Action);return}const m=e.target.closest('[data-v16-mode]');if(m){e.preventDefault();openMode(m.dataset.v16Mode);return}const f=e.target.closest('[data-v16-filter]');if(f){e.preventDefault();filter=f.dataset.v16Filter;document.querySelectorAll('[data-v16-filter]').forEach(x=>x.classList.toggle('active',x===f));paintList()}},true);document.addEventListener('input',e=>{if(e.target.id==='v16Search'){query=e.target.value;paintList()}},true);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeLibrary()});window.addEventListener('lumera:languagechange',()=>{renderDashboard();if(!$('v16Library')?.classList.contains('hidden'))openLibrary(filter)})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
