(function(){
'use strict';
const $=id=>document.getElementById(id);
const LANG='lumera_language_v13';
const t=(pt,en)=>localStorage.getItem(LANG)==='en'?en:pt;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const read=(k,f=[])=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch(e){return f}};
const fmt=d=>{try{return new Date(d).toLocaleString(localStorage.getItem(LANG)==='en'?'en-CA':'pt-BR',{dateStyle:'medium',timeStyle:'short'})}catch(e){return String(d||'')}};
const STORE={sessions:'rt_sessions_v4',assessments:'rt_assessments_v1',divorces:'rt_divorce_sessions_v1'};
const FINDINGS='lumera_current_findings_v20';
let historyViewMode='timeline',historyFilter='all',historyQuery='';
function saveFindings(){const items=[...document.querySelectorAll('#priorityList .check[data-tag]')].map(x=>({tag:x.dataset.tag,label:x.querySelector('b')?.textContent?.trim()||x.dataset.tag,command:x.querySelector('small')?.textContent?.replace(/^Comando sugerido:\s*/i,'').trim()||''}));if(items.length)localStorage.setItem(FINDINGS,JSON.stringify(items))}
function currentFindings(){return read(FINDINGS,[])}
function causalDeferred(){return [...document.querySelectorAll('#causalPlan .causalPlanItem')].filter(x=>/não tratar nesta sessão|not treat/i.test(x.textContent||'')).map(x=>x.querySelector('b')?.textContent?.trim()).filter(Boolean)}
function decorateCausalChoice(){const title=$('causalTitle');if(!title)return;const isTreat=/deve ser tratado nesta sessão|treated in this session/i.test(title.textContent||'');const buttons=[...document.querySelectorAll('#causalAnswers [data-causal]')];if(isTreat&&buttons.length>=2){buttons[0].textContent=t('Tratar agora','Treat now');buttons[1].textContent=t('Adiar','Defer');const ctx=$('causalContext');if(ctx&&!ctx.querySelector?.('.v20CausalHint')){ctx.insertAdjacentHTML('beforeend',`<span class="v20CausalHint">${t(' • “Adiar” mantém o achado registrado, mas não abre campos de tratamento nesta sessão.',' • “Defer” keeps the finding recorded, but does not open treatment fields in this session.')}</span>`)}}else if(buttons.length>=2){buttons[0].textContent=t('Sim','Yes');buttons[1].textContent=t('Não','No')}}
function showView(id){['homeView','startView','questionView','priorityView','causalView','treatmentView','reportView','historyView'].forEach(v=>$(v)?.classList.add('hidden'));$(id)?.classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}
function recoverTreatment(){const host=$('treatmentItems');if(!host||$('treatmentView')?.classList.contains('hidden'))return;const findings=currentFindings(),deferred=causalDeferred();const cards=host.querySelectorAll('.treatmentCard').length;if(!cards&&findings.length){host.innerHTML=`<section class="card v20TreatmentRecovery"><span class="pill">${t('Revisão necessária','Review needed')}</span><h3>${t('Há achados identificados, mas nenhum foi marcado para tratamento.','Findings were identified, but none were marked for treatment.')}</h3><p>${t('Os achados não foram perdidos. Revise a decisão “Tratar agora / Adiar” antes de concluir a sessão.','Your findings were not lost. Review the “Treat now / Defer” decision before completing the session.')}</p><div class="v20FindingList">${findings.map(x=>`<div><b>${esc(x.label)}</b>${x.command?`<small>${esc(x.command)}</small>`:''}</div>`).join('')}</div><button type="button" class="primary wide" id="v20ReviewTreatment">${t('Revisar seleção de tratamento','Review treatment selection')}</button></section>`;$('v20ReviewTreatment').onclick=()=>showView('priorityView');return}
 let summary=$('v20TreatmentSummary');summary?.remove();if(cards&&findings.length){summary=document.createElement('section');summary.id='v20TreatmentSummary';summary.className='v20TreatmentSummary';summary.innerHTML=`<b>${cards} ${t('item(ns) para tratar agora','item(s) to treat now')}</b><span>${findings.length} ${t('achado(s) identificado(s)','identified finding(s)')}${deferred.length?` • ${deferred.length} ${t('adiado(s)','deferred')}`:''}</span>`;host.before(summary)}
 const old=$('v20Deferred');old?.remove();if(deferred.length){const d=document.createElement('details');d.id='v20Deferred';d.className='card v20Deferred';d.innerHTML=`<summary>${t('Ver achados adiados nesta sessão','View findings deferred in this session')} (${deferred.length})</summary><div>${deferred.map(x=>`<p>• ${esc(x)}</p>`).join('')}</div><button type="button" class="ghost wide" id="v20ReviewDeferred">${t('Revisar decisões','Review decisions')}</button>`;host.after(d);d.querySelector('#v20ReviewDeferred').onclick=()=>showView('priorityView')}
}
function identityForAssessment(a){const i=a?.identity||{};if(i.sessionType==='collective'){const p=(i.participants||[]).filter(x=>x.name);return p.length?p.map(x=>x.name).join(', '):t('Sessão coletiva','Group session')}return i.name||t('Sem cliente vinculado','Unlinked client')}
function records(){const assessments=read(STORE.assessments),sessions=read(STORE.sessions),divorces=read(STORE.divorces),used=new Set(),out=[];sessions.forEach(s=>{const a=assessments.find(x=>String(x.linkedSessionId)===String(s.id));if(a)used.add(String(a.id));out.push({id:'s:'+s.id,kind:'protocol',date:s.date,title:s.title||s.mode||t('Protocolo','Protocol'),name:a?identityForAssessment(a):t('Sem cliente vinculado','Unlinked client'),status:'completed',session:s,assessment:a})});assessments.filter(a=>!used.has(String(a.id))).forEach(a=>out.push({id:'a:'+a.id,kind:'assessment',date:a.updatedAt||a.createdAt,title:t('Avaliação inicial','Initial assessment'),name:identityForAssessment(a),status:(a.status==='draft'||a.status==='protocol-pending')?'draft':'completed',assessment:a}));divorces.forEach(d=>{const p=(d.people||[]).filter(x=>x.name);out.push({id:'d:'+d.id,kind:'divorce',date:d.updatedAt||d.createdAt,title:t('Divórcio Energético','Energetic Divorce'),name:p.length?p.map(x=>x.name).join(', '):t('Sem cliente vinculado','Unlinked client'),status:d.status==='draft'?'draft':'completed',divorce:d})});return out.sort((a,b)=>new Date(b.date||0)-new Date(a.date||0))}
function kindLabel(r){return r.kind==='protocol'?t('Protocolo','Protocol'):r.kind==='assessment'?t('Avaliação','Assessment'):t('Divórcio Energético','Energetic Divorce')}
function shortSummary(r){if(r.kind==='protocol'){const s=r.session;return `${s.initial??'—'}% → ${s.final??'—'}% • ${(s.findings||[]).length} ${t('achado(s)','finding(s)')} • ${(s.treatment||[]).length} ${t('tratado(s)','treated')}`}if(r.kind==='assessment'){const vals=Object.values(r.assessment?.lifeAreas||{}).filter(v=>v!==''&&v!=null).map(Number);return vals.length?t('Maior desequilíbrio: ','Highest imbalance: ')+Math.max(...vals)+'%':t('Avaliação registrada','Assessment recorded')}const d=r.divorce;return `${Object.values(d?.initial||{}).filter(v=>v===true).length} ${t('área(s) identificada(s)','identified area(s)')}`}
function recordCard(r){return `<button type="button" class="v20Record" data-v20-record="${esc(r.id)}"><div class="v20RecordTop"><span>${esc(kindLabel(r))}</span><em class="${r.status==='draft'?'draft':''}">${r.status==='draft'?t('Rascunho','Draft'):t('Concluído','Completed')}</em></div><h3>${esc(r.name)}</h3><strong>${esc(r.title)}</strong><p>${esc(shortSummary(r))}</p><small>${esc(fmt(r.date))}</small><b class="v20Open">${t('Abrir ficha','Open record')} ›</b></button>`}
function matches(r){if(historyFilter==='draft'&&r.status!=='draft')return false;if(historyFilter==='individual'&&r.name.includes(','))return false;if(historyFilter==='group'&&!r.name.includes(','))return false;if(!historyQuery)return true;return [r.name,r.title,shortSummary(r)].join(' ').toLocaleLowerCase().includes(historyQuery.toLocaleLowerCase())}
function renderHistory(){const hv=$('historyView'),box=$('historyList');if(!hv||hv.classList.contains('hidden')||!box)return;hv.querySelector('.historyHead h2').textContent=t('Clientes e Histórico','Clients & History');const intro=hv.querySelector(':scope > p.muted');if(intro)intro.textContent=t('Abra uma ficha para rever investigação, achados, tratamento, gráficos, observações e resultados.','Open a record to review investigation, findings, treatment, charts, notes and results.');const rs=records().filter(matches);box.innerHTML=`<div class="v20HistoryTools"><input id="v20HistorySearch" type="search" value="${esc(historyQuery)}" placeholder="${t('Buscar cliente, protocolo ou tema…','Search client, protocol or topic…')}"><div class="v20HistoryFilters"><button data-v20-filter="all" class="${historyFilter==='all'?'active':''}">${t('Todos','All')}</button><button data-v20-filter="individual" class="${historyFilter==='individual'?'active':''}">${t('Individuais','Individual')}</button><button data-v20-filter="group" class="${historyFilter==='group'?'active':''}">${t('Coletivos','Groups')}</button><button data-v20-filter="draft" class="${historyFilter==='draft'?'active':''}">${t('Rascunhos','Drafts')}</button></div></div><div class="v20Records">${rs.length?rs.map(recordCard).join(''):`<div class="v20Empty">${t('Nenhum registro encontrado.','No records found.')}</div>`}</div>`;$('v20HistorySearch').oninput=e=>{historyQuery=e.target.value;renderHistory()};box.querySelectorAll('[data-v20-filter]').forEach(b=>b.onclick=()=>{historyFilter=b.dataset.v20Filter;renderHistory()})}
function qaAnswers(s){const data=window.DATA?.[s.mode]?.questions||[];const by=new Map(data.map(q=>[q.id,q]));return Object.entries(s.answers||{}).map(([id,v])=>{const q=by.get(id);return q?`<div class="v20QA"><span>${esc(q.q)}</span><b>${v==='yes'?t('Sim','Yes'):t('Não','No')}</b></div>`:''}).join('')}
function treatmentHTML(s){const caus=s.causal?.items||[];const treated=s.treatment||[];const findings=(s.findings||[]).map(tag=>{const p=window.PLANS?.[tag];const it=caus.find(x=>x.tag===tag);const tr=treated.find(x=>x.tag===tag||x.id===it?.id);return `<div class="v20Finding ${tr?'treated':'deferred'}"><div><b>${esc(p?.label||tag)}</b><small>${tr?t('Tratado nesta sessão','Treated in this session'):t('Identificado • não tratado nesta sessão','Identified • not treated in this session')}</small></div>${tr?`<p><strong>${t('Comando','Command')}:</strong> ${esc(tr.command||'')}</p>${(tr.graphs||[]).map(g=>`<p><strong>${t('Gráfico','Chart')}:</strong> ${esc(g.name||'—')} ${g.quantity?`• ${esc(g.quantity)} ${esc(g.unit||'')}`:''}</p>`).join('')}${tr.notes?`<p><strong>${t('Observações','Notes')}:</strong> ${esc(tr.notes)}</p>`:''}`:''}</div>`}).join('');return findings||`<p class="muted">${t('Nenhum achado registrado.','No findings recorded.')}</p>`}
function detailHTML(r){if(r.kind==='protocol'){const s=r.session;return `<div class="v20SheetHero"><span>${esc(kindLabel(r))}</span><h2>${esc(r.title)}</h2><p>${esc(r.name)} • ${esc(fmt(r.date))}</p></div><div class="v20Metrics"><div><small>${t('Antes','Before')}</small><b>${s.initial??'—'}%</b></div><div><small>${t('Depois','After')}</small><b>${s.final??'—'}%</b></div><div><small>${t('Achados','Findings')}</small><b>${(s.findings||[]).length}</b></div></div><section><h3>${t('Achados e tratamento','Findings & treatment')}</h3>${treatmentHTML(s)}</section><details><summary>${t('Ver respostas da investigação','View investigation answers')}</summary><div class="v20QAs">${qaAnswers(s)||`<p>${t('Respostas não disponíveis.','Answers unavailable.')}</p>`}</div></details>${s.generalNotes?`<section><h3>${t('Observações gerais','General notes')}</h3><p>${esc(s.generalNotes)}</p></section>`:''}`}
 if(r.kind==='assessment'){const a=r.assessment;return `<div class="v20SheetHero"><span>${esc(kindLabel(r))}</span><h2>${esc(r.title)}</h2><p>${esc(r.name)} • ${esc(fmt(r.date))}</p></div><section><h3>${t('Relato','Notes')}</h3><p>${esc(a.identity?.relato||t('Não registrado','Not recorded'))}</p></section><section><h3>${t('Áreas da vida','Life areas')}</h3>${Object.entries(a.lifeAreas||{}).map(([k,v])=>v!==''?`<p><b>${esc(k)}</b>: ${esc(v)}%</p>`:'').join('')||`<p>${t('Não aferidas.','Not measured.')}</p>`}</section>`}
 const d=r.divorce;return `<div class="v20SheetHero"><span>${esc(kindLabel(r))}</span><h2>${esc(r.title)}</h2><p>${esc(r.name)} • ${esc(fmt(r.date))}</p></div><section><h3>${t('Tema','Theme')}</h3><p>${esc(d.theme||t('Não registrado','Not recorded'))}</p></section><section><h3>${t('Áreas identificadas','Identified areas')}</h3>${Object.entries(d.initial||{}).filter(([,v])=>v===true).map(([k])=>`<p>• ${esc(k)}</p>`).join('')||`<p>${t('Nenhuma registrada.','None recorded.')}</p>`}</section>`}
function openRecord(id){const r=records().find(x=>x.id===id);if(!r)return;let o=$('v20RecordSheet');if(!o){o=document.createElement('div');o.id='v20RecordSheet';o.className='v20Overlay';document.body.appendChild(o)}o.innerHTML=`<div class="v20Sheet"><button type="button" class="v20SheetClose" aria-label="${t('Fechar','Close')}">×</button>${detailHTML(r)}</div>`;o.classList.add('open');document.body.classList.add('v20ModalOpen');o.querySelector('.v20SheetClose').onclick=closeRecord;o.onclick=e=>{if(e.target===o)closeRecord()}}
function closeRecord(){$('v20RecordSheet')?.classList.remove('open');document.body.classList.remove('v20ModalOpen')}
function state(){const visible=id=>$(id)&&!$(id).classList.contains('hidden');document.body.classList.toggle('v20TreatmentOpen',visible('treatmentView'));document.body.classList.toggle('v20HistoryOpen',visible('historyView'));document.body.classList.toggle('v20ReportOpen',visible('reportView'))}
function install(){document.addEventListener('click',e=>{if(e.target.closest('#toTreatmentBtn'))setTimeout(saveFindings,0);const rec=e.target.closest('[data-v20-record]');if(rec){e.preventDefault();openRecord(rec.dataset.v20Record)}});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeRecord()});let timer;new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(()=>{state();decorateCausalChoice();if(!$('priorityView')?.classList.contains('hidden'))saveFindings();recoverTreatment();renderHistory()},70)}).observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['class']});window.addEventListener('storage',()=>{renderHistory();recoverTreatment()});window.addEventListener('lumera:languagechange',()=>{renderHistory();recoverTreatment();decorateCausalChoice()});state();decorateCausalChoice();renderHistory();recoverTreatment()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();