(function(){
'use strict';
const $=id=>document.getElementById(id);
const I=()=>window.LumeraI18n;
const t=(k,v)=>I()?.t(k,v)||k;
const ASSESS='rt_assessments_v1',DIV='rt_divorce_sessions_v1',DRAFT='lumera_protocol_draft_v14';
const GROUPS={resources:['finance','prosperity','career','creativity'],relations:['marriage','family','social','parenting'],self:['selfworth','bodyrelation','purpose','repeating','homeenv'],quick:['quick_balance','quick_hardday','quick_decision','quick_cycle','quick_conflict'],master:['master']};
let filter='all',query='';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function read(k,fallback){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(fallback))}catch(e){return fallback}}
function latest(arr,pred){return (Array.isArray(arr)?arr:[]).filter(pred||(()=>true)).sort((a,b)=>new Date(b.updatedAt||b.createdAt||0)-new Date(a.updatedAt||a.createdAt||0))[0]||null}
function announce(msg){let live=$('lumeraLive');if(!live){live=document.createElement('div');live.id='lumeraLive';live.className='v16SrOnly';live.setAttribute('role','status');live.setAttribute('aria-live','polite');document.body.appendChild(live)}live.textContent='';requestAnimationFrame(()=>live.textContent=msg)}
function waitFor(id,tries=12){return new Promise(resolve=>{let n=0;const tick=()=>{const el=$(id);if(el)return resolve(el);if(++n>=tries)return resolve(null);setTimeout(tick,80)};tick()})}
async function clickExisting(id){const el=await waitFor(id);if(!el){announce(t('status.unavailable'));return false}el.click();return true}
function modeGroup(mode){for(const [g,modes] of Object.entries(GROUPS))if(modes.includes(mode))return g;return'master'}
function allModes(){return [...new Set(Object.values(GROUPS).flat())]}
function modeTitle(mode){return window.DATA?.[mode]?.title||document.querySelector(`[data-open-mode="${mode}"] strong`)?.textContent||mode}
function modeCopy(mode){return document.querySelector(`[data-open-mode="${mode}"] small`)?.textContent||''}
function draft(){const a=latest(read(ASSESS,[]),x=>x?.status==='draft'||x?.status==='protocol-pending'),d=latest(read(DIV,[]),x=>x?.status==='draft'),p=read(DRAFT,null);const items=[];if(a)items.push({type:'assessment',date:a.updatedAt||a.createdAt,item:a});if(d)items.push({type:'divorce',date:d.updatedAt||d.createdAt,item:d});if(p)items.push({type:'protocol',date:p.updatedAt||p.createdAt,item:p});return items.sort((x,y)=>new Date(y.date||0)-new Date(x.date||0))[0]||null}
function draftName(d){if(!d)return'';if(d.type==='protocol')return modeTitle(d.item.mode);if(d.type==='divorce')return (d.item.people||[]).find(p=>p.name)?.name||t('action.divorce');const id=d.item.identity||{};return id.sessionType==='collective'?((id.participants||[]).filter(p=>p.name).map(p=>p.name).join(', ')||t('action.assessment')):(id.name||t('action.assessment'))}
function dashboardHTML(){const d=draft();return `<section class="v16Dashboard" aria-labelledby="v16Title"><div class="v16Head"><span>${esc(t('home.eyebrow'))}</span><h1 id="v16Title">${esc(t('home.title'))}</h1><p>${esc(t('home.copy'))}</p></div>${d?`<button class="v16Resume" type="button" data-v16-action="resume"><span aria-hidden="true">↻</span><span><small>${esc(t('resume.title'))}</small><strong>${esc(draftName(d))}</strong><em>${esc(t('resume.'+d.type))}</em></span><b aria-hidden="true">›</b></button>`:''}<div class="v16Actions"><button type="button" data-v16-action="assessment" class="v16Action v16Primary"><span aria-hidden="true">＋</span><strong>${esc(t('action.assessment'))}</strong><small>${esc(t('action.assessment.copy'))}</small></button><button type="button" data-v16-action="library" class="v16Action"><span aria-hidden="true">◎</span><strong>${esc(t('action.protocol'))}</strong><small>${esc(t('action.protocol.copy'))}</small></button><button type="button" data-v16-action="divorce" class="v16Action"><span aria-hidden="true">↯</span><strong>${esc(t('action.divorce'))}</strong><small>${esc(t('action.divorce.copy'))}</small></button><button type="button" data-v16-action="quick" class="v16Action"><span aria-hidden="true">◌</span><strong>${esc(t('action.quick'))}</strong><small>${esc(t('action.quick.copy'))}</small></button></div><div class="v16Secondary"><button type="button" class="ghost" data-v16-action="history">${esc(t('action.history'))}</button><button type="button" class="ghost" data-v16-action="practitioner">${esc(t('action.practitioner'))}</button></div></section>`}
function renderDashboard(){const home=$('homeView');if(!home)return;home.classList.add('v16Home');let host=$('v16Dashboard');if(!host){host=document.createElement('div');host.id='v16Dashboard';home.prepend(host)}host.innerHTML=dashboardHTML()}
function ensureLibrary(){let o=$('v16Library');if(o)return o;o=document.createElement('div');o.id='v16Library';o.className='v16Overlay hidden';o.setAttribute('role','dialog');o.setAttribute('aria-modal','true');o.setAttribute('aria-labelledby','v16LibraryTitle');document.body.appendChild(o);return o}
function libraryHTML(){const labels={all:'library.all',resources:'library.resources',relations:'library.relations',self:'library.self',quick:'library.quick',master:'library.master'};return `<div class="v16Sheet"><div class="v16SheetHead"><div><span>Lumera</span><h2 id="v16LibraryTitle">${esc(t('library.title'))}</h2><p>${esc(t('library.copy'))}</p></div><button type="button" data-v16-action="close-library" class="v16Close" aria-label="${esc(t('library.close'))}">×</button></div><label class="v16Search"><span class="v16SrOnly">${esc(t('library.search'))}</span><input id="v16Search" type="search" value="${esc(query)}" placeholder="${esc(t('library.search'))}" autocomplete="off"></label><div class="v16Filters" role="group" aria-label="${esc(t('library.title'))}">${Object.entries(labels).map(([k,l])=>`<button type="button" data-v16-filter="${k}" aria-pressed="${filter===k}" class="${filter===k?'active':''}">${esc(t(l))}</button>`).join('')}</div><div id="v16List" class="v16List"></div><div class="v16Master"><div><strong>${esc(t('library.unsure'))}</strong><small>${esc(t('library.unsure.copy'))}</small></div><button type="button" class="ghost" data-v16-mode="master">${esc(t('library.openMaster'))}</button></div></div>`}
function paintList(){const host=$('v16List');if(!host)return;const q=query.trim().toLocaleLowerCase();const modes=allModes().filter(m=>filter==='all'||modeGroup(m)===filter).filter(m=>!q||`${modeTitle(m)} ${modeCopy(m)}`.toLocaleLowerCase().includes(q));host.innerHTML=modes.length?modes.map(m=>`<button type="button" class="v16Protocol" data-v16-mode="${esc(m)}"><span aria-hidden="true">${modeGroup(m)==='quick'?'◌':modeGroup(m)==='master'?'◎':'✦'}</span><span><strong>${esc(modeTitle(m))}</strong><small>${esc(modeCopy(m))}</small></span><b aria-hidden="true">›</b></button>`).join(''):`<div class="v16Empty">${esc(t('library.empty'))}</div>`}
function openLibrary(which='all'){filter=which;query='';const o=ensureLibrary();o.innerHTML=libraryHTML();o.classList.remove('hidden');document.body.classList.add('v16ModalOpen');paintList();requestAnimationFrame(()=>$('v16Search')?.focus())}
function closeLibrary(){const o=$('v16Library');if(o)o.classList.add('hidden');document.body.classList.remove('v16ModalOpen');document.querySelector('[data-v16-action="library"]')?.focus()}
async function openMode(mode){closeLibrary();announce(t('status.loading'));let src=document.querySelector(`#homeView [data-open-mode="${CSS.escape(mode)}"]`)||document.querySelector(`[data-open-mode="${CSS.escape(mode)}"]`);if(src){src.click();return}const tab=document.querySelector(`.tab[data-mode="${CSS.escape(mode)}"]`);if(tab){tab.click();await new Promise(r=>setTimeout(r,30));src=document.querySelector(`[data-open-mode="${CSS.escape(mode)}"]`);if(src){src.click();return}}announce(t('status.unavailable'))}
async function resume(){const d=draft();if(!d)return;if(d.type==='protocol'){const b=$('v14ProtocolResume');if(b){b.click();return}return openMode(d.item.mode)}if(d.type==='assessment'){await clickExisting('historyBtn');setTimeout(()=>{const b=document.querySelector(`[data-resume="${CSS.escape(String(d.item.id))}"]`);if(b)b.click();else clickExisting('startAssessmentBtn')},120);return}await clickExisting('historyBtn')}
async function act(action){switch(action){case'assessment':return clickExisting('startAssessmentBtn');case'library':return openLibrary('all');case'divorce':return clickExisting('openDivorceBtn');case'quick':return openLibrary('quick');case'history':return clickExisting('historyBtn');case'practitioner':document.querySelector('.lumeraWorkspace')?.scrollIntoView({behavior:'smooth',block:'start'});return;case'resume':return resume();case'close-library':return closeLibrary()}}
function sessionActive(){return['startView','questionView','priorityView','causalView','treatmentView','assessmentView','reevalView','divorceView'].some(id=>{const e=$(id);return e&&!e.classList.contains('hidden')})}
function ensureSessionToggle(){let b=$('v16SessionToggle');if(!b){b=document.createElement('button');b.id='v16SessionToggle';b.type='button';b.className='v16SessionToggle hidden';b.addEventListener('click',()=>{const on=!document.body.classList.contains('v16Focus');document.body.classList.toggle('v16Focus',on);b.setAttribute('aria-pressed',String(on));b.querySelector('span').textContent=t(on?'sessionMode.off':'sessionMode.on')});b.innerHTML='<span>'+esc(t('sessionMode.on'))+'</span>';document.body.appendChild(b)}const active=sessionActive();b.classList.toggle('hidden',!active);if(!active){document.body.classList.remove('v16Focus');b.setAttribute('aria-pressed','false');b.querySelector('span').textContent=t('sessionMode.on')}}
function a11y(){document.querySelector('main')?.setAttribute('aria-label',t('a11y.main'));document.querySelectorAll('button').forEach(b=>{if(!b.getAttribute('type'))b.setAttribute('type','button')});document.querySelectorAll('input,textarea,select').forEach(el=>{if(!el.getAttribute('aria-label')&&!el.id&&!el.closest('label')){const lab=el.previousElementSibling?.textContent?.trim();if(lab)el.setAttribute('aria-label',lab)}});const footer=document.querySelector('footer .lumeraCredit')||document.querySelector('footer');if(footer){if(footer.classList.contains('lumeraCredit'))footer.textContent=t('footer.credit');else{let c=footer.querySelector('.v16Credit');if(!c){c=document.createElement('div');c.className='v16Credit';footer.appendChild(c)}c.textContent=t('footer.credit')}}document.title=t('app.title')}
function installEvents(){document.addEventListener('click',e=>{const a=e.target.closest('[data-v16-action]');if(a){e.preventDefault();act(a.dataset.v16Action);return}const m=e.target.closest('[data-v16-mode]');if(m){e.preventDefault();openMode(m.dataset.v16Mode);return}const f=e.target.closest('[data-v16-filter]');if(f){e.preventDefault();filter=f.dataset.v16Filter;document.querySelectorAll('[data-v16-filter]').forEach(x=>{x.classList.toggle('active',x===f);x.setAttribute('aria-pressed',String(x===f))});paintList()}},true);document.addEventListener('input',e=>{if(e.target.id==='v16Search'){query=e.target.value;paintList()}},true);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('v16Library')?.classList.contains('hidden'))closeLibrary()})}
function render(){renderDashboard();ensureSessionToggle();a11y()}
function install(){ensureLibrary();installEvents();render();let timer;new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(()=>{if($('homeView')&&!$('homeView').classList.contains('hidden'))renderDashboard();ensureSessionToggle();a11y()},60)}).observe(document.body,{subtree:true,attributes:true,attributeFilter:['class']});window.addEventListener('lumera:languagechange',()=>{render();if(!$('v16Library')?.classList.contains('hidden')){const o=$('v16Library');o.innerHTML=libraryHTML();paintList()}});window.addEventListener('storage',()=>{if($('homeView')&&!$('homeView').classList.contains('hidden'))renderDashboard()});new MutationObserver(()=>{render();if(!$('v16Library')?.classList.contains('hidden')){const o=$('v16Library');o.innerHTML=libraryHTML();paintList()}}).observe(document.documentElement,{attributes:true,attributeFilter:['lang']})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
