Object.assign(PLANS,{
seguranca_relacao:{label:'Segurança e proteção no relacionamento',command:'Não tratar violência, ameaça, coerção, abuso ou controle apenas como questão energética. Priorizar segurança, apoio adequado e medidas concretas de proteção antes de qualquer trabalho simbólico.'},
crencas_relacao:{label:'Crenças limitantes sobre relacionamento',command:'Eliminar e ressignificar crenças limitantes sobre amor, casamento, confiança e intimidade que dificultem uma relação saudável, recíproca e respeitosa.'},
medo_abandono:{label:'Medo de abandono ou rejeição',command:'Limpar padrões de medo de abandono, rejeição ou perda que gerem controle, afastamento ou reatividade, fortalecendo segurança interna e vínculo saudável.'},
ressentimento:{label:'Ressentimentos e mágoas',command:'Trabalhar ressentimentos e mágoas ainda ativos, favorecendo elaboração, limites, reparação possível e liberação do que já não precisa permanecer no vínculo.'},
feridas_passadas:{label:'Feridas afetivas passadas',command:'Ressignificar feridas de relações anteriores, infância ou experiências passadas que estejam sendo projetadas no casamento atual.'},
autovalor_relacao:{label:'Autovalor afetivo',command:'Fortalecer autoestima, merecimento afetivo e capacidade de receber amor sem dependência, submissão ou autoabandono.'},
comunicacao:{label:'Bloqueios de comunicação',command:'Limpar padrões que bloqueiam comunicação clara e respeitosa e fortalecer escuta, expressão emocional e diálogo orientado à solução.'},
necessidades_nao_expressas:{label:'Necessidades não expressas',command:'Favorecer identificação e expressão clara de necessidades, sentimentos e expectativas, reduzindo suposições e ressentimentos acumulados.'},
ciclo_conflito:{label:'Ciclo repetitivo de conflito',command:'Interromper o ciclo recorrente de crítica, defesa, silêncio, afastamento ou escalada e fortalecer pausas, reparação e comunicação segura.'},
confianca:{label:'Fragilidade de confiança',command:'Trabalhar os fatores que fragilizam a confiança e fortalecer consistência, transparência, acordos e segurança relacional.'},
segredos:{label:'Mentiras, omissões ou segredos',command:'Trazer clareza aos padrões de ocultação relevantes e favorecer honestidade, responsabilização e acordos compatíveis com a segurança do vínculo.'},
infidelidade:{label:'Feridas por quebra de acordos ou infidelidade',command:'Trabalhar a ferida da quebra de confiança, priorizando verdade, responsabilização, limites e decisão consciente sobre reconstrução do vínculo.'},
distancia_emocional:{label:'Distanciamento emocional',command:'Reduzir padrões de afastamento emocional e fortalecer presença, disponibilidade, curiosidade e conexão entre o casal.'},
falta_afeto:{label:'Falta de carinho e reconhecimento',command:'Fortalecer reconhecimento, gratidão, afeto e demonstrações cotidianas de cuidado compatíveis com as necessidades de ambos.'},
intimidade:{label:'Desequilíbrio de intimidade',command:'Trabalhar barreiras à intimidade afetiva e física com respeito, consentimento, segurança e comunicação.'},
desejo_desalinhado:{label:'Desalinhamento de desejo',command:'Favorecer diálogo sem pressão sobre diferenças de desejo e necessidades de intimidade, respeitando consentimento, limites e fatores físicos ou emocionais relevantes.'},
expectativas:{label:'Expectativas conjugais incompatíveis',command:'Clarificar e renegociar expectativas sobre papéis, parceria, compromisso e funcionamento do casamento.'},
carga_relacional:{label:'Desequilíbrio de tarefas e carga mental',command:'Reequilibrar responsabilidades, carga mental e tarefas do relacionamento com acordos claros e percepção de justiça por ambos.'},
financas_casal:{label:'Conflitos financeiros do casal',command:'Reduzir padrões de conflito financeiro e fortalecer transparência, metas comuns, limites e responsabilidade compartilhada.'},
parentalidade:{label:'Conflitos de parentalidade',command:'Favorecer alinhamento, respeito e acordos parentais consistentes sem transformar divergências sobre filhos em ataques ao vínculo conjugal.'},
tempo_casal:{label:'Falta de tempo e presença',command:'Restabelecer prioridade, presença e tempo de qualidade para o vínculo, de forma realista e consistente.'},
pressao_externa:{label:'Pressões externas sobre o casamento',command:'Reduzir o impacto de estresse externo sobre o vínculo e fortalecer proteção do relacionamento, comunicação e divisão de cargas.'},
interferencia_terceiros:{label:'Interferência de familiares ou terceiros',command:'Fortalecer fronteiras do casal e reduzir interferências externas incompatíveis com os acordos e a autonomia do relacionamento.'},
saude_transicao:{label:'Saúde e transições de vida',command:'Reconhecer e tratar concretamente fatores de saúde ou fase de vida que estejam afetando o relacionamento, ajustando expectativas e suporte mútuo.'},
padrao_familiar_relacao:{label:'Padrões conjugais transgeracionais',command:'Interromper a repetição de padrões familiares de abandono, infidelidade, conflito, submissão, frieza ou separação que já não sejam funcionais.'},
lealdade_relacao:{label:'Lealdades familiares afetivas',command:'Liberar lealdades familiares que associem pertencimento à repetição de destinos afetivos dolorosos, preservando vínculo familiar sem reproduzir o padrão.'},
crencas_herdadas_relacao:{label:'Crenças afetivas herdadas',command:'Identificar, questionar e ressignificar crenças herdadas sobre casamento, amor, fidelidade, sexo e papéis conjugais que não correspondam aos valores atuais do casal.'},
votos_relacao:{label:'Votos, promessas ou juramentos — relacionamento',command:'Dentro da minha prática espiritual, identificar e liberar votos, promessas ou juramentos que eu considere incompatíveis com um vínculo afetivo saudável, mantendo apenas compromissos alinhados aos valores atuais.'},
pactos_relacao:{label:'Pactos ou contratos simbólicos — relacionamento',command:'Dentro da minha prática espiritual, revisar e encerrar simbolicamente pactos, contratos ou acordos que eu considere prejudiciais ao equilíbrio do relacionamento atual.'},
karma_relacao:{label:'Padrões interpretados como kármicos — relacionamento',command:'Dentro da minha prática espiritual, trabalhar e ressignificar padrões que interpreto como kármicos relacionados a amor, confiança, intimidade ou vínculo conjugal.'},
vinculos_relacao:{label:'Vínculos ou cargas energéticas — relacionamento',command:'Dentro da minha prática espiritual, limpar e equilibrar vínculos ou cargas energéticas percebidas como prejudiciais ao relacionamento, reforçando limites, centramento e autonomia.'},
outra_relacao:{label:'Outra causa raiz do relacionamento',command:'Aprofundar a investigação com perguntas binárias até delimitar natureza, origem e manifestação da causa; formular um comando específico somente depois de identificá-la.'}
});

DATA.marriage={title:'Casamento / Relacionamento',copy:'Investigue fatores individuais, dinâmica do casal, pressões externas, padrões familiares/ancestrais e, dentro da sua prática, aspectos espirituais ou simbólicos. Questões concretas de segurança, saúde e confiança devem ser tratadas também no mundo real.',questions:[
Q('m_safety','Realidade concreta','Há violência, ameaça, coerção, abuso ou controle que coloque alguém em risco?','seguranca_relacao'),
Q('m_internal','Origem','Há fatores internos individuais contribuindo para o desequilíbrio do casamento?'),
Q('m_beliefs','Interno • Crenças','Há crenças limitantes sobre amor, casamento, confiança, intimidade ou merecimento afetivo?','crencas_relacao','m_internal'),
Q('m_abandon','Interno • Emoções','Há medo de abandono, rejeição, perda ou não ser amado(a) influenciando a relação?','medo_abandono','m_internal'),
Q('m_resent','Interno • Emoções','Há ressentimentos, mágoas ou dificuldade de perdão ainda ativos entre o casal?','ressentimento','m_internal'),
Q('m_past','Interno • Experiências','Há feridas de relações anteriores, infância ou experiências passadas interferindo no casamento atual?','feridas_passadas','m_internal'),
Q('m_selfworth','Interno • Identidade','Há baixa autoestima, insegurança ou dificuldade de receber amor afetando o vínculo?','autovalor_relacao','m_internal'),
Q('m_couple','Dinâmica do casal','Há fatores na dinâmica atual do casal contribuindo para o desequilíbrio?'),
Q('m_comm','Comunicação','Há bloqueios de comunicação entre o casal?','comunicacao','m_couple'),
Q('m_needs','Comunicação','Há necessidades, sentimentos ou expectativas importantes que não estão sendo expressos claramente?','necessidades_nao_expressas','m_comm'),
Q('m_cycle','Comunicação','Há ciclos repetitivos de crítica, defesa, silêncio, afastamento ou conflito que o casal não consegue interromper?','ciclo_conflito','m_comm'),
Q('m_trust','Confiança','Há quebra ou fragilidade de confiança entre o casal?','confianca','m_couple'),
Q('m_secrets','Confiança','Há mentiras, omissões, segredos ou comportamentos ocultos afetando o vínculo?','segredos','m_trust'),
Q('m_betray','Confiança','Há feridas relacionadas a infidelidade ou quebra de acordos do relacionamento ainda ativas?','infidelidade','m_trust'),
Q('m_connection','Conexão emocional','Há distanciamento emocional ou sensação de desconexão entre o casal?','distancia_emocional','m_couple'),
Q('m_appreciation','Conexão emocional','Há falta de reconhecimento, carinho, gratidão ou demonstrações de afeto no cotidiano?','falta_afeto','m_connection'),
Q('m_intimacy','Intimidade','Há desequilíbrio na intimidade física, afetiva ou sexual do casal?','intimidade','m_couple'),
Q('m_desire','Intimidade','Há diferença de desejo, frequência ou necessidades de intimidade que esteja gerando sofrimento ou afastamento?','desejo_desalinhado','m_intimacy'),
Q('m_roles','Papéis e expectativas','Há expectativas incompatíveis sobre papéis, responsabilidades ou funcionamento do casamento?','expectativas','m_couple'),
Q('m_load','Papéis e expectativas','Há desequilíbrio percebido na divisão de tarefas, carga mental ou responsabilidades?','carga_relacional','m_roles'),
Q('m_money','Papéis e expectativas','Há conflitos financeiros afetando a relação?','financas_casal','m_roles'),
Q('m_parenting','Papéis e expectativas','Há conflitos relacionados a filhos, educação ou parentalidade afetando o casamento?','parentalidade','m_roles'),
Q('m_time','Conexão','Há falta de tempo de qualidade, prioridade ou presença dedicada ao relacionamento?','tempo_casal','m_couple'),
Q('m_external','Origem','Há fatores externos contribuindo para o desequilíbrio do casamento?'),
Q('m_stress','Externo • Pressões','Há estresse de trabalho, finanças, saúde, mudança de vida ou sobrecarga interferindo na relação?','pressao_externa','m_external'),
Q('m_family','Externo • Família','Há interferência de familiares, amigos ou terceiros nos limites e decisões do casal?','interferencia_terceiros','m_external'),
Q('m_health','Externo • Saúde e fase de vida','Há questões de saúde física, mental, hormonal, pós-parto, luto ou transições de vida afetando o relacionamento?','saude_transicao','m_external'),
Q('m_ancestral','Origem','Há fatores familiares, ancestrais ou transgeracionais relacionados ao desequilíbrio do casamento?'),
Q('m_familymodel','Ancestralidade','Há repetição de padrões familiares de conflito, abandono, infidelidade, submissão, frieza ou separação?','padrao_familiar_relacao','m_ancestral'),
Q('m_loyalty','Ancestralidade','Há lealdades invisíveis ou necessidade de repetir destinos afetivos do sistema familiar?','lealdade_relacao','m_ancestral'),
Q('m_inherited','Ancestralidade','Há crenças herdadas sobre casamento, homens, mulheres, amor, fidelidade, sexo ou papéis conjugais influenciando o casal?','crencas_herdadas_relacao','m_ancestral'),
Q('m_spiritual','Origem','Dentro da sua prática ou sistema de crenças, há fatores espirituais, simbólicos ou energéticos relacionados ao casamento?'),
Q('m_vows','Espiritual / simbólico','Há votos, promessas ou juramentos que, dentro da sua prática, estejam associados a sofrimento afetivo, solidão, submissão ou impedimento de vínculo saudável?','votos_relacao','m_spiritual'),
Q('m_pacts','Espiritual / simbólico','Há pactos, contratos, acordos ou compromissos simbólicos que devam ser investigados em relação ao casamento?','pactos_relacao','m_spiritual'),
Q('m_karma','Espiritual / simbólico','Há padrões interpretados pela sua prática como kármicos relacionados ao vínculo do casal, amor, confiança ou intimidade?','karma_relacao','m_spiritual'),
Q('m_ties','Espiritual / simbólico','Há vínculos, cordões, influências ou cargas energéticas que, dentro da sua prática, devam ser tratados para favorecer limites e equilíbrio no relacionamento?','vinculos_relacao','m_spiritual'),
Q('m_other','Causa raiz','Há alguma outra causa raiz relevante para o casamento que ainda não foi identificada por este protocolo?','outra_relacao')
]};