import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('.',import.meta.url);
const starter=fs.readFileSync(new URL('./graph-starter-library.js',root),'utf8');
const form=fs.readFileSync(new URL('./treatment-create-ui.js',root),'utf8');
const management=fs.readFileSync(new URL('./treatment-item-management-ui.js',root),'utf8');
const prefill=fs.readFileSync(new URL('./root-treatment-prefill-ui.js',root),'utf8');
const css=fs.readFileSync(new URL('./treatment-item-graphs.css',root),'utf8');
const html=fs.readFileSync(new URL('./index.html',root),'utf8');
for(const name of ['Prosperador','Luxor','Scap','Neutralize','Flor da Vida','Abundância Financeira','Forma Yave','Escudo Bouclier'])assert.ok(starter.includes(name),`Starter library should include ${name}.`);
assert.match(starter,/type:'GRAPH'/);
assert.match(starter,/tags:\[\]/,'Starter graphs must not impose categories yet.');
assert.match(form,/data-treatment-item/);
assert.match(form,/data-treatment-command/);
assert.match(form,/data-treatment-graph/);
assert.match(form,/list="fluxa-treatment-graphs"/,'Graph field should suggest the library while remaining free text.');
assert.match(form,/Adicione pelo menos um item de tratamento/);
assert.match(management,/data-backlog-add-component/,'Existing treatment add flow must be intercepted by the item model.');
assert.match(management,/data-backlog-replace-component/,'Existing treatment replace flow must use the item model.');
assert.match(prefill,/Escolha ao menos um gráfico para cada comando/,'Protocol prefill must populate topic and command, not misuse the graph field.');
assert.match(css,/overflow-anchor:none/,'Guided protocol should disable scroll anchoring during answer transitions.');
assert.match(css,/contain:layout paint/,'Question panel should keep a stable layout between Sim/Não answers.');
assert.ok(html.indexOf('treatment-item-graphs.css')<html.indexOf('brand-shell.css'),'Treatment graph CSS must preserve the final brand shell authority.');
assert.ok(html.includes('graph-starter-library.js'));
assert.ok(html.includes('treatment-item-management-ui.js'));
console.log('graph-starter-library.test.mjs: ok');
