import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('.',import.meta.url);
const read=(p)=>fs.readFileSync(new URL(p,root),'utf8');
const html=read('./index.html'),ui=read('./premium-workflow-ui.js'),css=read('./premium-workflow.css'),itemCss=read('./treatment-item-graphs.css'),trace=read('./traceability-ui.js');
assert.ok(html.includes('premium-workflow.css'),'Premium workflow CSS must load.');
assert.ok(html.includes('premium-workflow-ui.js'),'Premium workflow UI must load.');
assert.ok(html.indexOf('premium-workflow.css')>html.indexOf('premium-reference.css'),'Workflow CSS must load after the reference layer.');
assert.ok(html.indexOf('brand-shell.css')>html.indexOf('premium-workflow.css'),'Global brand shell must remain the final global stylesheet.');
assert.ok(html.indexOf('premium-workflow-ui.js')>html.indexOf('premium-shell-ui.js'),'Workflow UI must run after premium shell cleanup.');
assert.match(ui,/querySelectorAll\('\.treatment-card\[data-treatment-id\]'\)/);
assert.match(ui,/premium-treatment-components/);
assert.match(ui,/treatmentItemView/,'Premium treatment cards must understand the item → command → graph model and legacy records.');
assert.match(ui,/durationLabel/,'Each graph must render its own duration or review state.');
assert.match(ui,/premium-item-graphs/,'Commands must expose their graph applications in the treatment preview.');
assert.match(ui,/preview\.replaceWith\(next\)/,'Treatment enhancement must replace its preview instead of duplicating it.');
assert.match(ui,/premium-protocol-kicker/);
assert.match(ui,/requestAnimationFrame/,'Observer work should be frame-coalesced.');
assert.match(css,/premium-component-progress/);
assert.match(css,/premium-workflow-protocol \.question-panel/);
assert.match(css,/grid-template-columns:1fr 1fr/);
assert.match(css,/treatment-trace-disclosure/,'Treatment provenance must use progressive disclosure instead of permanent long copy.');
assert.match(css,/#backlog-overlay \.detail-sheet\{min-height:0/,'Component manager must not force a nearly full-height detail sheet.');
assert.match(css,/#backlog-overlay \.detail-sheet>\.stack>\.card \.button-row/,'Component actions must remain compact and touch-friendly.');
assert.match(trace,/document\.createElement\('details'\)/,'Treatment origin must be collapsible.');
assert.match(trace,/Origem da investigação/);
assert.doesNotMatch(trace,/<strong>Origem:<\/strong>/,'Treatment card must not permanently render verbose provenance.');
assert.match(itemCss,/premium-item-command/);
assert.match(itemCss,/premium-item-graphs/);
assert.doesNotMatch(`${css}\n${itemCss}`,/gold|purple|violet|cosmic/i);
console.log('premium-workflow.test.mjs: ok');