import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('.',import.meta.url);
const read=(p)=>fs.readFileSync(new URL(p,root),'utf8');
const html=read('./index.html'),ui=read('./premium-workflow-ui.js'),css=read('./premium-workflow.css');
assert.ok(html.includes('premium-workflow.css'),'Premium workflow CSS must load.');
assert.ok(html.includes('premium-workflow-ui.js'),'Premium workflow UI must load.');
assert.ok(html.indexOf('premium-workflow.css')>html.indexOf('premium-reference.css'),'Workflow CSS must load after the reference layer.');
const brand=html.indexOf('brand-shell.css'),workflow=html.indexOf('premium-workflow.css'),idle=html.indexOf('idle-home-premium.css');
assert.ok(workflow>brand,'Workflow-specific styling must load after the global brand shell.');
if(idle>=0)assert.ok(idle>workflow,'Idle Home specialization may remain after the workflow layer.');
assert.ok(html.indexOf('premium-workflow-ui.js')>html.indexOf('premium-shell-ui.js'),'Workflow UI must run after premium shell cleanup.');
assert.match(ui,/querySelectorAll\('\.treatment-card\[data-treatment-id\]'\)/);
assert.match(ui,/premium-treatment-components/);
assert.ok(ui.includes('.slice(0,3)'),'Treatment preview must stay compact at a maximum of three components.');
assert.match(ui,/preview\.replaceWith\(next\)/,'Treatment enhancement must replace its preview instead of duplicating it.');
assert.match(ui,/durationRemaining/);
assert.match(ui,/premium-protocol-kicker/);
assert.match(ui,/requestAnimationFrame/,'Observer work should be frame-coalesced.');
assert.match(css,/premium-component-progress/);
assert.match(css,/premium-workflow-protocol \.question-panel/);
assert.match(css,/grid-template-columns:1fr 1fr/);
assert.doesNotMatch(css,/gold|purple|violet|cosmic/i);
console.log('premium-workflow.test.mjs: ok');
