import assert from 'node:assert/strict';
import fs from 'node:fs';
const source=fs.readFileSync(new URL('./root-treatment-prefill-ui.js',import.meta.url),'utf8');
const catalogFix=fs.readFileSync(new URL('./catalog-featured-fix-ui.js',import.meta.url),'utf8');
assert.match(catalogFix,/import '\.\/root-treatment-prefill-ui\.js'/,'Catalog integration must load thematic treatment prefill.');
assert.match(source,/data-root-handoff-treatment/,'Prefill must start from the root-protocol treatment handoff.');
assert.match(source,/suggestedTreatmentTitle/,'Suggested treatment titles from root protocols must feed treatment items.');
assert.match(source,/suggestedTreatmentCommand/,'Suggested treatment commands from root protocols must feed commands.');
assert.match(source,/form\.dataset\.findings=pending\.findingIds\.join\(','\)/,'Treatment must preserve Finding → Treatment traceability.');
assert.match(source,/\[data-treatment-items\] > \[data-treatment-item\]/,'Multiple thematic findings must become multiple treatment items.');
assert.match(source,/form\.dataset\.thematicPrefill='true'/,'The prefilled form must expose its thematic origin.');
assert.match(source,/Escolha ao menos um gráfico para cada comando/,'Protocol suggestions must not be written into the graph-name field.');
assert.match(source,/Sugestões do protocolo aplicadas/,'Therapist must be told that protocol suggestions were applied and remain editable.');
console.log('root-treatment-prefill.test.mjs: ok');
