import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('.',import.meta.url),repo=new URL('../',root);
const read=(p)=>fs.readFileSync(new URL(p,root),'utf8');
const readRepo=(p)=>fs.readFileSync(new URL(p,repo),'utf8');
const html=read('./index.html'),adapter=read('./legacy-protocol-adapter.js'),catalog=read('./therapeutic-catalog-ui.js'),divorce=read('./divorce-energy-fluxa-ui.js'),divorceDomain=read('./divorce-energy-domain.js'),premium=read('./premium-reference.css'),shell=read('./premium-shell-ui.js'),home=read('./home-refresh-ui.js'),sw=read('./service-worker.js');
const readme=readRepo('./README.md'),legacyApp=readRepo('./app.js'),marriage=readRepo('./marriage.js'),core=readRepo('./protocols-v11-core.js'),expansion=readRepo('./protocols-v11-expansion.js'),quick=readRepo('./protocols-v11-quick.js');
for(const file of ['premium-reference.css','legacy-protocol-adapter.js','therapeutic-catalog-ui.js','divorce-energy-fluxa-ui.js','premium-shell-ui.js'])assert.ok(html.includes(file),`index must load ${file}`);
assert.ok(html.indexOf('premium-reference.css')>html.indexOf('brand-refresh.css'),'Premium reference CSS must load after the canonical Deep Teal layer.');
assert.ok(html.indexOf('premium-shell-ui.js')>html.indexOf('home-refresh-ui.js'),'Premium shell cleanup must run after Home enhancers.');
const rootSources=['../app.js','../marriage.js','../deep-tree.js','../deep-tree-2.js','../protocols-v11-core.js','../protocols-v11-expansion.js','../protocols-v11-quick.js'];
for(const source of rootSources)assert.ok(adapter.includes(source),`Root catalog adapter must read ${source}`);
assert.match(adapter,/kind:'ROOT_PROTOCOL'/);assert.match(adapter,/legacyPlanCommand/);assert.match(adapter,/suggestedTreatmentCommand/);assert.match(adapter,/applyRootProtocolMutations/);
assert.match(adapter,/let failedPaths=\[\]/,'Root protocol loading must track transient source and mutation failures.');
assert.match(adapter,/if\(catalog\.length&&failedPaths\.length===0\)return catalog/,'A complete root protocol catalog should be reused without unnecessary reloads.');
assert.match(adapter,/failures\.push\(source\.path\)/,'Unavailable protocol sources must be tracked.');
assert.match(adapter,/failures\.push\(mutation\.path\)/,'Unavailable deep-tree mutations must be tracked.');
assert.match(adapter,/finally\{loadingPromise=null;\}/,'The root catalog load promise must be released so later chooser opens can retry.');
assert.match(adapter,/rootProtocolCatalogStatus/,'Root catalog completeness must be inspectable for diagnostics.');
assert.match(adapter,/complete:failedPaths\.length===0/,'Root-protocol-ready events must expose complete versus partial catalog state.');
assert.match(catalog,/ensureRootProtocolCatalog\(\)/,'Opening a fresh investigation chooser must re-enter the loader and retry a previous partial catalog.');
for(const title of ['Vida Financeira','Carreira / Profissional','Casamento / Relacionamento','Autoestima, Amor-próprio e Merecimento','Relacionamentos Familiares','Prosperidade e Abundância','Propósito e Caminho de Vida','Casa e Ambiente','Relacionamento com o Próprio Corpo','Criatividade e Projetos','Vida Social e Pertencimento','Parentalidade','Padrões Repetitivos','Limpeza e Reequilíbrio','Reequilíbrio após um Dia Difícil','Preparação para uma Decisão Importante','Encerramento de Ciclo','Reequilíbrio após Conflito'])assert.ok(readme.includes(title)||legacyApp.includes(title)||marriage.includes(title)||core.includes(title)||expansion.includes(title)||quick.includes(title),`Root source should preserve ${title}`);
assert.match(catalog,/Testemunho/);assert.match(catalog,/Por tema|THEME_FILTERS/);assert.match(catalog,/Divórcio Energético/);assert.match(catalog,/Protocolo Mestre de Causa Raiz/);assert.match(catalog,/data-therapeutic-search/);
assert.match(catalog,/function searchTokens/,'Protocol discovery must tokenize multi-word searches.');
assert.match(catalog,/query\.every\(term=>text\.includes\(term\)\)/,'All typed protocol-search terms must match regardless of adjacency/order.');
assert.match(catalog,/theme\.some\(term=>text\.includes\(term\)\)/,'Theme chips should retain broad OR matching within a theme.');
assert.doesNotMatch(catalog,/queryOk=!query\|\|text\.includes\(query\)/,'Protocol search must not require one contiguous query substring.');
assert.match(divorce,/Relacionamentos amorosos/);assert.match(divorce,/Ex-relacionamentos e prosperidade/);assert.match(divorce,/Testemunho preparado/);assert.match(divorce,/suggestedTreatmentCommand/);
assert.match(divorceDomain,/Tratamento geral/);assert.match(divorceDomain,/Corte geral/);assert.match(divorceDomain,/validateDivorceEnergyDraft/);assert.match(divorceDomain,/divorceEnergyFindings/);
assert.match(shell,/O que você deseja fazer agora\?/);assert.match(shell,/grid\.hidden=true/);assert.match(shell,/fluxa-brand-mark/);
assert.match(home,/home-action-icon/);assert.match(home,/Ações principais da sessão/);assert.match(home,/btn\.textContent='Atividade'/);assert.match(home,/close\.textContent='Encerrar'/);
assert.match(premium,/\.home-primary-actions\{[^}]*repeat\(4,minmax\(0,1fr\)\)/,'Mobile workspace should expose four compact primary shortcuts.');
assert.match(premium,/\.home-action-icon\{/);assert.match(premium,/background:transparent/);assert.match(premium,/featured-protocol-grid/);assert.match(premium,/therapeutic-witness-note/);assert.match(premium,/premium-protocol-sheet \.question-panel/);assert.doesNotMatch(premium,/purple|violet|cosmic|gold/i);
for(const source of rootSources)assert.ok(sw.includes(source),`Service worker must precache ${source}`);
assert.match(sw,/isFluxaSupportUrl/);assert.match(sw,/therapeutic-catalog-complete-20260821/);
console.log('therapeutic-catalog.test.mjs: ok');
