import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('.',import.meta.url);
const read=(p)=>fs.readFileSync(new URL(p,root),'utf8');
const loader=read('./ux-architecture-loader.js');
const css=read('./validation-round-5.css');
const ui=read('./validation-round-5-ui.js');
assert.match(loader,/validation-round-5-ui\.js/,'Round 5 must load in the UX architecture bundle.');
assert.ok(loader.indexOf('validation-round-5-ui.js')>loader.indexOf('validation-round-4-ui.js'),'Round 5 must load after round 4.');
assert.match(css,/grid-template-columns:minmax\(82px,104px\) 44px minmax\(0,1fr\) 44px/,'Open-session phone header must reserve four one-row control columns.');
assert.match(css,/mobile-duration-presets[\s\S]*flex-wrap:wrap/,'Duration presets must wrap instead of clipping on phones.');
assert.match(css,/home-recent-history-hidden[\s\S]*display:none/,'Idle Home recent activity must remain hidden.');
assert.match(css,/hawkins-scale-popover\{display:none!important;\}/,'The legacy focus popover must not compete with the iOS keyboard.');
assert.match(ui,/Sessão · /,'Open-session indicator must use compact mobile copy.');
assert.match(ui,/Atividade recente/,'Round 5 must detect and remove idle Home activity.');
assert.match(ui,/resetWorkspaceScroll/,'Workspace route changes must reset stale scroll position.');
assert.match(ui,/Escolher na escala de Hawkins/,'Hawkins entry points must expose an explicit scale control.');
assert.match(ui,/data-round5-hawkins-choice/,'The mobile Hawkins scale must provide selectable levels.');
console.log('validation-round-5.test.mjs: ok');
