import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('.',import.meta.url);
const read=(p)=>fs.readFileSync(new URL(p,root),'utf8');
const loader=read('./ux-architecture-loader.js');
const css=read('./validation-round-4.css');
const ui=read('./validation-round-4-ui.js');
assert.match(loader,/validation-round-4-ui\.js/,'Mobile reconciliation layer must load.');
assert.ok(loader.indexOf('validation-round-4-ui.js')>loader.indexOf('validation-round-3-ui.js'),'Mobile reconciliation must load last.');
assert.match(ui,/Atividade recente/,'Idle Home activity block must be detected for removal from Hoje.');
assert.match(ui,/home-recent-history-hidden/,'Idle Home history content must be moved out of the action-first Home surface.');
assert.match(css,/\.prep-mobile-reconciled>\.checklist/,'Preparation checkpoints must compact on phones.');
assert.match(css,/#findings-form \.finding-classification-inline/,'Finding classification must receive a phone-specific full-width layout.');
assert.match(css,/flex-direction:column!important/,'Mobile finding classification must stack label and select instead of collapsing text.');
assert.match(css,/\.mobile-treatment-compose-footer/,'Treatment compose footer must be reconciled on phones.');
assert.match(css,/position:static!important/,'Treatment submit summary must not float over form content on phones.');
assert.match(css,/body:has\(\.modal-backdrop\) \.workspace-bottom-nav/,'Bottom navigation must not compete with an open modal on phones.');
assert.match(css,/\.topbar:has\(\.session-indicator\) \.brand/,'Open-session header must preserve brand contrast.');
console.log('validation-round-4.test.mjs: ok');
