import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('.',import.meta.url);
const read=(p)=>fs.readFileSync(new URL(p,root),'utf8');
const loader=read('./ux-architecture-loader.js'),css=read('./validation-round-3.css'),ui=read('./validation-round-3-ui.js');
assert.match(loader,/validation-round-3-ui\.js/,'Final validation layer must load after theme system.');
assert.ok(loader.indexOf('validation-round-3-ui.js')>loader.indexOf('theme-system-ui.js'),'Final validation layer must load after theme system.');
assert.match(css,/\.topbar\{display:flex!important/,'Desktop header must use one stable horizontal row.');
assert.match(css,/grid-template-columns:repeat\(4,minmax\(0,1fr\)\)!important/,'Bottom navigation must keep four equal destinations.');
assert.match(css,/\.finding-classification-inline\{grid-column:1\/-1!important/,'Finding classification must never collapse into a narrow vertical column.');
assert.match(css,/grid-template-columns:120px minmax\(220px,1fr\)!important/,'Desktop finding classification must preserve usable select width.');
assert.match(css,/html\[data-fluxa-theme="FRESH_ENERGY"\] body\.fluxa-home-idle \.hero-card/,'Fresh Energy must visually override legacy idle-home scaffolding.');
assert.match(css,/\.premium-workflow-protocol \.question-panel\{min-height:300px!important/,'Quick triage must avoid excessive empty desktop height.');
assert.match(ui,/\[700,'Iluminação'\]/);assert.match(ui,/\[600,'Paz'\]/);assert.match(ui,/\[540,'Alegria'\]/);assert.match(ui,/\[500,'Amor'\]/);assert.match(ui,/\[400,'Razão'\]/);assert.match(ui,/\[350,'Aceitação'\]/);assert.match(ui,/\[310,'Boa vontade'\]/);assert.match(ui,/\[250,'Neutralidade'\]/);assert.match(ui,/\[200,'Coragem'\]/);assert.match(ui,/\[175,'Orgulho'\]/);assert.match(ui,/\[150,'Raiva'\]/);assert.match(ui,/\[125,'Desejo'\]/);assert.match(ui,/\[100,'Medo'\]/);assert.match(ui,/\[75,'Tristeza'\]/);assert.match(ui,/\[50,'Apatia'\]/);assert.match(ui,/\[30,'Culpa'\]/);assert.match(ui,/\[20,'Vergonha'\]/);
assert.match(ui,/HAWKINS_SELECTOR=.*data-prep-frequency/,'Therapist Hawkins must use the shared scale picker.');
assert.match(ui,/data-hawkins-baseline-form/,'Assisted baseline must use the shared scale picker.');
assert.match(ui,/final-assessment-form/,'Final Hawkins must use the shared scale picker.');
assert.match(ui,/Buscar gráfico \/ recurso/,'Preparation must use a compact searchable graph/resource launcher.');
assert.match(ui,/select\.hidden=true/,'Long native preparation select must be hidden after searchable enhancement.');
console.log('validation-round-3.test.mjs: ok');
